; Library for RCEFShaders 1.5

namespace = RCEFShaders

[Constants]
global $HasSceneDepth = 0

[ResourceSceneDepth]

; Implementation ---------------------------

[Present]
post $HasSceneDepth = 0

[CommandListCaptureSceneDepth]
if $HasSceneDepth == 0
	ResourceSceneDepth = ref ps-t1
	$HasSceneDepth = 1
endif

; Source shaders ---------------------------

[ShaderOverride_4d4aeaba77c8835c]
hash = 4d4aeaba77c8835c
allow_duplicate_hash = true
run = CommandListCaptureSceneDepth

[ShaderOverride_17b280fb09bf16fd]
hash = 17b280fb09bf16fd
allow_duplicate_hash = true
run = CommandListCaptureSceneDepth

[ShaderOverride_e5c79df0d5b00481]
hash = e5c79df0d5b00481
allow_duplicate_hash = true
run = CommandListCaptureSceneDepth

[ShaderOverride_37eacbc3c84bb392]
hash = 37eacbc3c84bb392
allow_duplicate_hash = true
run = CommandListCaptureSceneDepth