; Library for RCEFShaders 1.5

namespace = RCEFShaders

[Constants]
global $HasViewConstants = 0

global $CameraCB_Offset = 0
global $CameraCB_Size = 0

global $FrameCB_Offset = 0
global $FrameCB_Size = 0

[ResourceCameraCB]

[ResourceFrameCB]

; Implementation ---------------------------

[Present]
post $HasViewConstants = 0

[CommandListCaptureViewConstants]
if $HasViewConstants == 0
	$CameraCB_Offset = vs-CB0->Offset
	$CameraCB_Size = vs-CB0->Size
	ResourceCameraCB = ref vs-CB0

	$FrameCB_Offset = vs-CB1->Offset
	$FrameCB_Size = vs-CB1->Size
	ResourceFrameCB = ref vs-CB1

	$HasViewConstants = 1
endif

; Source shaders ---------------------------

[ShaderOverride_5204669b553b0cda]
hash = 5204669b553b0cda
allow_duplicate_hash = true
run = CommandListCaptureViewConstants

[ShaderOverride_40426f24c41b60b9]
hash = 40426f24c41b60b9
allow_duplicate_hash = true
run = CommandListCaptureViewConstants