; Library for RCEFShaders

namespace = RCEFLibrary

[ResourceViewportSize]
type = Texture2D
format = R8_UNORM
array = 1
mips = 1
msaa = 1

; Implementation ---------------------------

[Present]
ResourceViewportSize = copy_description bb