; For RCEFShaders

namespace = RCEFCore

[Constants]
; Configurable
global persist $PanelPosX = 0.2
global persist $PanelPosY = 0.2
global $PanelSizeX = 0.4
global $PanelSizeY = 0.4
global $AnchorSizeX = 0.02
global $AnchorSizeY = 0.02

global $PaddingSizeX = 0.01
global $PaddingSizeY = 0.01
global $DividerSizeY = 0.002

; DO NOT configure these
global $IsOpen = 0
global $IsDragging = 0
global $AllowDragging = 0
global $TexelSize = 16 / 1080
global $AspectRatio = 1
global $OffsetY = 0

[KeyShowMenu]
key = VK_MENU VK_END
type = cycle
$IsOpen = 0, 1

[KeyDragMenu]
condition = $AllowDragging
key = VK_LBUTTON
type = hold
$IsDragging = 1

[Present]
if $IsOpen && window_width > 0 && window_height > 0
	$AspectRatio = window_width / window_height

	$AllowDragging = cursor_x >= $PanelPosX && cursor_x <= $PanelPosX + $AnchorSizeX && cursor_y >= $PanelPosY && cursor_y <= $PanelPosY + $AnchorSizeY * $AspectRatio
	if $IsDragging
		$PanelPosX = cursor_x - ($AnchorSizeX / 2)
		$PanelPosY = cursor_y - ($AnchorSizeY / 2) * $AspectRatio

		if $PanelPosX > 1 - $AnchorSizeX
			$PanelPosX = 1 - $AnchorSizeX
		endif
		if $PanelPosX < 0
			$PanelPosX = 0
		endif

		if $PanelPosY > 1 - ($AnchorSizeY * $AspectRatio)
			$PanelPosY = 1 - ($AnchorSizeY * $AspectRatio)
		endif
		if $PanelPosY < 0
			$PanelPosY = 0
		endif
	endif

	$OffsetY = $PanelPosY

	local $savedX99 = x99
	local $savedY99 = y99
	local $savedZ99 = z99
	local $savedW99 = w99

	run = CustomShaderDrawMenuBase
	run = CustomShaderDrawDivider
	run = CommandListDrawTestText

	x99 = $savedX99
	y99 = $savedY99
	z99 = $savedZ99
	w99 = $savedW99
else
	$AllowDragging = 0
endif

[ResourceColorWhite]
type = Buffer
data = R32_FLOAT 1 1 1 1

[ResourceColorBlack]
type = Buffer
data = R32_FLOAT 0 0 0 1

[ResourceColorYellow]
type = Buffer
data = R32_FLOAT 1 1 0 1

[ResourceColorBase]
type = Buffer
data = R32_FLOAT 0.08 0.08 0.08 0.75

[ResourceColorDivider]
type = Buffer
data = R32_FLOAT 0.5 0.5 0.5 1

[CustomShaderDrawDivider]
vs = Shaders/Draw2D.hlsl
ps = Shaders/Draw2D.hlsl
hs = null
ds = null
gs = null
cull = none
topology = triangle_strip
blend = ADD SRC_ALPHA INV_SRC_ALPHA
o0 = set_viewport bb
x99 = $PanelPosX
y99 = $OffsetY
z99 = $PanelSizeX
w99 = $DividerSizeY * $AspectRatio
ps-cb0 = ref ResourceColorDivider
ps-t1 = null
draw = 4, 0
$OffsetY = $OffsetY + w99 + ($PaddingSizeY * $AspectRatio)

[CommandListDrawDefaultText]
Resource\RCEFText\Background = null
Resource\RCEFText\Color = ref ResourceColorWhite
run = CommandList\RCEFText\PrintText

[CommandListDrawSelectedText]
Resource\RCEFText\Background = ref ResourceColorYellow
Resource\RCEFText\Color = ref ResourceColorBlack
run = CommandList\RCEFText\PrintText

[ResourceMenuTitle]
type = Buffer
format = R8_UINT
data = "RCEFShaders"

[CustomShaderDrawMenuBase]
vs = Shaders/Draw2D.hlsl
ps = Shaders/Draw2D.hlsl
hs = null
ds = null
gs = null

cull = none
topology = triangle_strip
blend = ADD SRC_ALPHA INV_SRC_ALPHA
o0 = set_viewport bb

x99 = $PanelPosX
y99 = $PanelPosY
z99 = $PanelSizeX
w99 = $PanelSizeY * $AspectRatio
ps-cb0 = ref ResourceColorBase
ps-t1 = null
draw = 4, 0

z99 = $AnchorSizeX
w99 = $AnchorSizeY * $AspectRatio
ps-cb0 = ref ResourceColorWhite
ps-t1 = null
draw = 4, 0

x99 = $PanelPosX + ($PanelSizeX / 2)
y99 = $PanelPosY + ($AnchorSizeY / 4) * $AspectRatio
z99 = 1
w99 = 2
Resource\RCEFText\Text = ref ResourceMenuTitle
Resource\RCEFText\Color = ref ResourceColorYellow
Resource\RCEFText\Background = null
run = CommandList\RCEFText\PrintText

$OffsetY = $OffsetY + ($TexelSize * w99) + ($PaddingSizeY * $AspectRatio)

[CommandListDrawTestText]
x99 = $PanelPosX + $AnchorSizeY
y99 = $OffsetY
z99 = 0
w99 = 1.5
Resource\RCEFText\Text = ref ResourceMenuTitle
run = CommandListDrawDefaultText

$OffsetY = $OffsetY + ($TexelSize * w99) + ($PaddingSizeY * $AspectRatio)

y99 = $OffsetY
Resource\RCEFText\Text = ref ResourceMenuTitle
run = CommandListDrawSelectedText

$OffsetY = $OffsetY + ($TexelSize * w99) + ($PaddingSizeY * $AspectRatio)