; Sub-Mod for RCEFShaders 1.5

; Feature Impl -----------------------------

[CommandListHideFoliage]
if $\RCEFShaders\HideFoliage == 1
	handling = skip
endif

; Foliage, LoD Dithering, and Shadow -------

[ShaderOverrideFoliageLoD_67518bb4058e8264]
hash = 67518bb4058e8264
allow_duplicate_hash = true
run = CommandListHideFoliage

[ShaderOverrideFoliage_2df0f2fbad540d70]
hash = 2df0f2fbad540d70
allow_duplicate_hash = true
run = CommandListHideFoliage

[ShaderOverrideFoliage_27723c38db51911f]
hash = 27723c38db51911f
allow_duplicate_hash = true
run = CommandListHideFoliage


[ShaderOverrideFoliage_b75a418376f8c231]
hash = b75a418376f8c231
allow_duplicate_hash = true
run = CommandListHideFoliage

[ShaderOverrideFoliage_cf81926350af380c]
hash = cf81926350af380c
allow_duplicate_hash = true
run = CommandListHideFoliage


[ShaderOverrideFoliage_8b7bcd0cde2e415a]
hash = 8b7bcd0cde2e415a
allow_duplicate_hash = true
run = CommandListHideFoliage

[ShaderOverrideFoliage_6112e6f58d76dff7]
hash = 6112e6f58d76dff7
allow_duplicate_hash = true
run = CommandListHideFoliage

[ShaderOverrideFoliage_0b3b267e742f34aa]
hash = 0b3b267e742f34aa
allow_duplicate_hash = true
run = CommandListHideFoliage


[ShaderOverrideFoliage_4a3b078bcba75e00]
hash = 4a3b078bcba75e00
allow_duplicate_hash = true
run = CommandListHideFoliage


[ShaderOverrideFoliage_9ac34157722995d3]
hash = 9ac34157722995d3
allow_duplicate_hash = true
run = CommandListHideFoliage


[ShaderOverrideFoliage_68c88a356d4e601e]
hash = 68c88a356d4e601e
allow_duplicate_hash = true
run = CommandListHideFoliage

; [ShaderOverrideFoliage_]
; hash = 
; allow_duplicate_hash = true
; run = CommandListHideFoliage

[ShaderOverrideFoliage_282ec289655564fa]
hash = 282ec289655564fa
allow_duplicate_hash = true
run = CommandListHideFoliage


[ShaderOverrideFoliage_ca70953c310127d7]
hash = ca70953c310127d7
allow_duplicate_hash = true
run = CommandListHideFoliage


[ShaderOverrideFoliage_379077334cc0fca0]
hash = 379077334cc0fca0
allow_duplicate_hash = true
run = CommandListHideFoliage


[ShaderOverrideFoliage_3d7f698d514f0e09]
hash = 3d7f698d514f0e09
allow_duplicate_hash = true
run = CommandListHideFoliage


[ShaderOverrideFoliage_b95ef760231ce972]
hash = b95ef760231ce972
allow_duplicate_hash = true
run = CommandListHideFoliage

[ShaderOverrideFoliage_2b11d48d2ca3e8a3]
hash = 2b11d48d2ca3e8a3
allow_duplicate_hash = true
run = CommandListHideFoliage

[ShaderOverrideFoliage_0fdf1ee6d06afe2b]
hash = 0fdf1ee6d06afe2b
allow_duplicate_hash = true
run = CommandListHideFoliage


[ShaderOverrideFoliage_5dc9ec9153c24fc5]
hash = 5dc9ec9153c24fc5
allow_duplicate_hash = true
run = CommandListHideFoliage

[ShaderOverrideFoliage_c17a1c3864d261f7]
hash = c17a1c3864d261f7
allow_duplicate_hash = true
run = CommandListHideFoliage

; [ShaderOverrideFoliage_]
; hash = 
; allow_duplicate_hash = true
; run = CommandListHideFoliage


[ShaderOverrideFoliage_92df8aea969da8c8]
hash = 92df8aea969da8c8
allow_duplicate_hash = true
run = CommandListHideFoliage

[ShaderOverrideFoliage_005cbcb7b592261d]
hash = 005cbcb7b592261d
allow_duplicate_hash = true
run = CommandListHideFoliage

; [ShaderOverrideFoliage_]
; hash = 
; allow_duplicate_hash = true
; run = CommandListHideFoliage


[ShaderOverrideFoliage_1153d987d9566dcb]
hash = 1153d987d9566dcb
allow_duplicate_hash = true
run = CommandListHideFoliage

[ShaderOverrideFoliage_99cb687e6c6f95c8]
hash = 99cb687e6c6f95c8
allow_duplicate_hash = true
run = CommandListHideFoliage

; [ShaderOverrideFoliage_]
; hash = 
; allow_duplicate_hash = true
; run = CommandListHideFoliage


[ShaderOverrideFoliage_6c906ba2b0fe19c0]
hash = 6c906ba2b0fe19c0
allow_duplicate_hash = true
run = CommandListHideFoliage

[ShaderOverrideFoliage_2d4c9774f67f68e8]
hash = 2d4c9774f67f68e8
allow_duplicate_hash = true
run = CommandListHideFoliage

; [ShaderOverrideFoliage_]
; hash = 
; allow_duplicate_hash = true
; run = CommandListHideFoliage


[ShaderOverrideFoliage_d317c1acafd3119d]
hash = d317c1acafd3119d
allow_duplicate_hash = true
run = CommandListHideFoliage

; [ShaderOverrideFoliage_]
; hash = 
; allow_duplicate_hash = true
; run = CommandListHideFoliage

; [ShaderOverrideFoliage_]
; hash = 
; allow_duplicate_hash = true
; run = CommandListHideFoliage


[ShaderOverrideFoliage_758976a822a417d3]
hash = 758976a822a417d3
allow_duplicate_hash = true
run = CommandListHideFoliage

; [ShaderOverrideFoliage_]
; hash = 
; allow_duplicate_hash = true
; run = CommandListHideFoliage

; [ShaderOverrideFoliage_]
; hash = 
; allow_duplicate_hash = true
; run = CommandListHideFoliage


[ShaderOverrideFoliage_dffc1662c198b77f]
hash = dffc1662c198b77f
allow_duplicate_hash = true
run = CommandListHideFoliage

; [ShaderOverrideFoliage_]
; hash = 
; allow_duplicate_hash = true
; run = CommandListHideFoliage

; [ShaderOverrideFoliage_]
; hash = 
; allow_duplicate_hash = true
; run = CommandListHideFoliage


; [ShaderOverrideFoliage_]
; hash = 
; allow_duplicate_hash = true
; run = CommandListHideFoliage

; [ShaderOverrideFoliage_]
; hash = 
; allow_duplicate_hash = true
; run = CommandListHideFoliage

; [ShaderOverrideFoliage_]
; hash = 
; allow_duplicate_hash = true
; run = CommandListHideFoliage


; [ShaderOverrideFoliage_]
; hash = 
; allow_duplicate_hash = true
; run = CommandListHideFoliage

; [ShaderOverrideFoliage_]
; hash = 
; allow_duplicate_hash = true
; run = CommandListHideFoliage

; [ShaderOverrideFoliage_]
; hash = 
; allow_duplicate_hash = true
; run = CommandListHideFoliage


; [ShaderOverrideFoliage_]
; hash = 
; allow_duplicate_hash = true
; run = CommandListHideFoliage

; [ShaderOverrideFoliage_]
; hash = 
; allow_duplicate_hash = true
; run = CommandListHideFoliage

; [ShaderOverrideFoliage_]
; hash = 
; allow_duplicate_hash = true
; run = CommandListHideFoliage


; [ShaderOverrideFoliage_]
; hash = 
; allow_duplicate_hash = true
; run = CommandListHideFoliage

; [ShaderOverrideFoliage_]
; hash = 
; allow_duplicate_hash = true
; run = CommandListHideFoliage

; [ShaderOverrideFoliage_]
; hash = 
; allow_duplicate_hash = true
; run = CommandListHideFoliage


; [ShaderOverrideFoliage_]
; hash = 
; allow_duplicate_hash = true
; run = CommandListHideFoliage

; [ShaderOverrideFoliage_]
; hash = 
; allow_duplicate_hash = true
; run = CommandListHideFoliage

; [ShaderOverrideFoliage_]
; hash = 
; allow_duplicate_hash = true
; run = CommandListHideFoliage


; [ShaderOverrideFoliage_]
; hash = 
; allow_duplicate_hash = true
; run = CommandListHideFoliage

; [ShaderOverrideFoliage_]
; hash = 
; allow_duplicate_hash = true
; run = CommandListHideFoliage

; [ShaderOverrideFoliage_]
; hash = 
; allow_duplicate_hash = true
; run = CommandListHideFoliage