; Sub-Mod for RCEFShaders 1.5

; Feature Impl -----------------------------

[CustomShaderFullAICRegions]
ps = FullAIC\AICRegions_5eacc3f1e20a6e04.hlsl
draw = from_caller

[ShaderOverrideFullAICRegions]
hash = 5eacc3f1e20a6e04
allow_duplicate_hash = true
if $\RCEFShaders\FullAICRegions == 1
	handling = skip
	run = CustomShaderFullAICRegions
endif


[CustomShaderFullAICTiles]
ps = FullAIC\AICTiles_700e02fb213abdcf.hlsl
draw = from_caller

[ShaderOverrideFullAICTiles]
hash = 700e02fb213abdcf
allow_duplicate_hash = true
if $\RCEFShaders\FullAICTiles == 1
	handling = skip
	run = CustomShaderFullAICTiles
endif