; Sub-Mod for RCEFShaders 1.5

; Feature Impl -----------------------------

[ResourceDistCullRange]
type = Buffer
format = R32G32B32A32_FLOAT
data = 30.0   0 0 0
;       ^     ^^^^^- Padding
;       ^- Cull Range

; Shadows ----------------------------------

[ShaderOverrideFoliageShadow_cdb50e453815869f]
hash = cdb50e453815869f
allow_duplicate_hash = true
if $\RCEFShaders\HideFoliage != 0
	handling = skip
endif

[ShaderOverrideFoliageShadow_19c629eca7e5b93f]
hash = 19c629eca7e5b93f
allow_duplicate_hash = true
if $\RCEFShaders\HideFoliage != 0
	handling = skip
endif

; There's technically also bamboo shadow but the shadows have their own LoD transition shader
; (Good job keeping your shader variants in check, HG) So I probably won't be hiding those shadows.
; You can find them via hunting mode if you want and PR it in if you find the transition hash.
; The hash for these shadows in question is 5bfd243b804318ca

; Near Distance ----------------------------

[CustomShaderDistCull_6bc5bd488c8043ff]
ps = HideFoliage\DistCull_6bc5bd488c8043ff.hlsl
ps-cb3 = ResourceDistCullRange
draw = from_caller

[ShaderOverrideFoliage_6bc5bd488c8043ff]
hash = 6bc5bd488c8043ff
allow_duplicate_hash = true
if $\RCEFShaders\HideFoliage != 0
	handling = skip
	if $\RCEFShaders\HideFoliage == 2
		run = CustomShaderDistCull_6bc5bd488c8043ff
	endif
endif


[CustomShaderDistCull_348034e5eb5d0798]
ps = HideFoliage\DistCull_348034e5eb5d0798.hlsl
ps-cb3 = ResourceDistCullRange
draw = from_caller

[ShaderOverrideFoliage_348034e5eb5d0798]
hash = 348034e5eb5d0798
allow_duplicate_hash = true
if $\RCEFShaders\HideFoliage != 0
	handling = skip
	if $\RCEFShaders\HideFoliage == 2
		run = CustomShaderDistCull_348034e5eb5d0798
	endif
endif


[CustomShaderDistCull_c48cead99cd3f6b3]
ps = HideFoliage\DistCull_c48cead99cd3f6b3.hlsl
ps-cb3 = ResourceDistCullRange
draw = from_caller

[ShaderOverrideFoliage_c48cead99cd3f6b3]
hash = c48cead99cd3f6b3
allow_duplicate_hash = true
if $\RCEFShaders\HideFoliage != 0
	handling = skip
	if $\RCEFShaders\HideFoliage == 2
		run = CustomShaderDistCull_c48cead99cd3f6b3
	endif
endif


[CustomShaderDistCull_c7c0343a36285f20]
ps = HideFoliage\DistCull_c7c0343a36285f20.hlsl
ps-cb3 = ResourceDistCullRange
draw = from_caller

[ShaderOverrideFoliage_c7c0343a36285f20]
hash = c7c0343a36285f20
allow_duplicate_hash = true
if $\RCEFShaders\HideFoliage != 0
	handling = skip
	if $\RCEFShaders\HideFoliage == 2
		run = CustomShaderDistCull_c7c0343a36285f20
	endif
endif

[CustomShaderDistCull_b21d73a68a3ea576]
ps = HideFoliage\DistCull_b21d73a68a3ea576.hlsl
ps-cb3 = ResourceDistCullRange
draw = from_caller

[ShaderOverrideFoliageLoD_b21d73a68a3ea576]
hash = b21d73a68a3ea576
allow_duplicate_hash = true
if $\RCEFShaders\HideFoliage != 0
	handling = skip
	if $\RCEFShaders\HideFoliage == 2
		run = CustomShaderDistCull_b21d73a68a3ea576
	endif
endif


[CustomShaderDistCull_80e99252170ac2ff]
ps = HideFoliage\DistCull_80e99252170ac2ff.hlsl
ps-cb3 = ResourceDistCullRange
draw = from_caller

[ShaderOverrideFoliage_80e99252170ac2ff]
hash = 80e99252170ac2ff
allow_duplicate_hash = true
if $\RCEFShaders\HideFoliage != 0
	handling = skip
	if $\RCEFShaders\HideFoliage == 2
		run = CustomShaderDistCull_80e99252170ac2ff
	endif
endif

[CustomShaderDistCull_74f183191821ce5a]
ps = HideFoliage\DistCull_74f183191821ce5a.hlsl
ps-cb3 = ResourceDistCullRange
draw = from_caller

[ShaderOverrideFoliageLoD_74f183191821ce5a]
hash = 74f183191821ce5a
allow_duplicate_hash = true
if $\RCEFShaders\HideFoliage != 0
	handling = skip
	if $\RCEFShaders\HideFoliage == 2
		run = CustomShaderDistCull_74f183191821ce5a
	endif
endif


[CustomShaderDistCull_f1a85f4972982608]
ps = HideFoliage\DistCull_f1a85f4972982608.hlsl
ps-cb3 = ResourceDistCullRange
draw = from_caller

[ShaderOverrideFoliage_f1a85f4972982608]
hash = f1a85f4972982608
allow_duplicate_hash = true
if $\RCEFShaders\HideFoliage != 0
	handling = skip
	if $\RCEFShaders\HideFoliage == 2
		run = CustomShaderDistCull_f1a85f4972982608
	endif
endif

[CustomShaderDistCull_539892c99ea80a74]
ps = HideFoliage\DistCull_539892c99ea80a74.hlsl
ps-cb3 = ResourceDistCullRange
draw = from_caller

[ShaderOverrideFoliageLoD_539892c99ea80a74]
hash = 539892c99ea80a74
allow_duplicate_hash = true
if $\RCEFShaders\HideFoliage != 0
	handling = skip
	if $\RCEFShaders\HideFoliage == 2
		run = CustomShaderDistCull_539892c99ea80a74
	endif
endif

; Far Distance -----------------------------

[CommandListHideFarFoliage]
if $\RCEFShaders\HideFoliage == 1
	handling = skip
endif

