; Sub-Mod for RCEFShaders 1.5

; Feature Impl -----------------------------

[CommandListHideGameUI]
if $\RCEFShaders\HideGameUI == 1
	handling = skip
endif

[ShaderOverrideGameUI01]
hash = 01259601012f89c3
allow_duplicate_hash = true
run = CommandListHideGameUI

[ShaderOverrideGameUI02]
hash = 0455377ec18d59bc
allow_duplicate_hash = true
run = CommandListHideGameUI

[ShaderOverrideGameUI03]
hash = 524a724a453fd672
allow_duplicate_hash = true
run = CommandListHideGameUI

[ShaderOverrideGameUI04]
hash = 54f066aab750db23
allow_duplicate_hash = true
run = CommandListHideGameUI

[ShaderOverrideGameUI05]
hash = bc279606858d5235
allow_duplicate_hash = true
run = CommandListHideGameUI

[ShaderOverrideGameUI06]
hash = f2dc00276bab2d84
allow_duplicate_hash = true
run = CommandListHideGameUI

[ShaderOverrideGameUI07]
hash = 7983dd7b33f4a115
allow_duplicate_hash = true
run = CommandListHideGameUI

[ShaderOverrideGameUI08]
hash = 8241579e34ea6fc2
allow_duplicate_hash = true
run = CommandListHideGameUI

[ShaderOverrideGameUI09]
hash = 31e6daaf8342d9b6
allow_duplicate_hash = true
run = CommandListHideGameUI

[ShaderOverrideGameUI10]
hash = dae7c6cdd8a78d51
allow_duplicate_hash = true
run = CommandListHideGameUI

[ShaderOverrideGameUI11]
hash = ee9c85fadead6f7a
allow_duplicate_hash = true
run = CommandListHideGameUI