; Sub-Mod for RCEFShaders 1.5

; Feature Impl -----------------------------

[CommandListHideFoliage]
if $\RCEFShaders\HideFoliage == 1
	handling = skip
endif

; Removes LOD dithering but causes severe motion vector artifacts
; [ShaderOverrideFoliage0]
; hash = efaae32cb873d5b7
; allow_duplicate_hash = true
; run = CommandListHideFoliage

[ShaderOverrideFoliage1]
hash = 80e99252170ac2ff
allow_duplicate_hash = true
run = CommandListHideFoliage

[ShaderOverrideFoliage2]
hash = c7c0343a36285f20
allow_duplicate_hash = true
run = CommandListHideFoliage

[ShaderOverrideFoliage3]
hash = d317c1acafd3119d
allow_duplicate_hash = true
run = CommandListHideFoliage

[ShaderOverrideFoliage4]
hash = f1a85f4972982608
allow_duplicate_hash = true
run = CommandListHideFoliage

[ShaderOverrideFoliage5]
hash = fb3e3687f6f13d21
allow_duplicate_hash = true
run = CommandListHideFoliage

[ShaderOverrideFoliage6]
hash = 348034e5eb5d0798
allow_duplicate_hash = true
run = CommandListHideFoliage

[ShaderOverrideFoliage7]
hash = 6bc5bd488c8043ff
allow_duplicate_hash = true
run = CommandListHideFoliage

[ShaderOverrideFoliage8]
hash = 99bcebc14e45250a
allow_duplicate_hash = true
run = CommandListHideFoliage

[ShaderOverrideFoliage9]
hash = c48cead99cd3f6b3
allow_duplicate_hash = true
run = CommandListHideFoliage

[ShaderOverrideFoliage10]
hash = 5bfd243b804318ca
allow_duplicate_hash = true
run = CommandListHideFoliage