; Sub-Mod for RCEFShaders 1.5

; Feature Impl -----------------------------

; Dynamic text buffer
[ResourceCoordinateText]
type = RWBuffer
format = R8_UINT
array = 128

[ResourceCoordinateParams]
type = StructuredBuffer
array = 1
data = R32_FLOAT  +0.50 +0.70 +0.98 +0.85   1.00 0.20 0.20 1.00   0.00 0.00 0.00 0.75   0.01  0.01   2 2   0   1.3
;                x1-^  y1-^  x2-^  y2-^   | R-^  G-^  B-^  A-^  | R-^  G-^  B-^  A-^  | ^-H    V-^ | ^ ^ | ^ |  ^- font scale
;                Rectangle (range -1:+1)  | Text Color          | Background Color    | Border     |  ^  | ^- text alignment: 0=left 1=center 2=right
;                                         |                     |                     |            |  ^- h/v-anchor: 0=none 1=left/top 2=center 3=right/bottom 

[CustomShaderCoordinateText]
cs = Misc/CameraCoordinate.hlsl
vs = null
ps = null
hs = null
ds = null
gs = null

cs-cb0 = ref Resource\RCEFShaders\CameraCB->Region($\RCEFShaders\CameraCB_Offset, $\RCEFShaders\CameraCB_Size)
cs-u0 = ResourceCoordinateText

dispatch = 1, 1, 1

cs-u0 = null
cs-cb0 = null

[CommandListDrawCoordinates]
run = CustomShaderCoordinateText

Resource\EFMIv1\Text = ref ResourceCoordinateText
Resource\EFMIv1\TextParams = ref ResourceCoordinateParams
run = CommandList\EFMIv1\PrintText

[Present]
if $\RCEFShaders\ShowCamCoords == 1 && $\RCEFShaders\HasViewConstants == 1
	run = CommandListDrawCoordinates
endif