; Sub-Mod for RCEFShaders 1.5

; Feature Impl -----------------------------

[Constants]
; EXPERIMENTAL: Makes Invisible walls behind other invisible walls not render to avoid visual clutter.
global $selfDepthTest = 0

global $wallMode = 0
global $canRender = 0

; Depth mask for self depth test -----------

[ResourceSelfDepthTexture]
type = Texture2D
format = DXGI_FORMAT_D32_FLOAT
array = 1
mips = 1
msaa = 1
bind_flags = depth_stencil

[CommandListPrepareSelfDepth]
; Copy the info from the backbody so we match the resolution
ResourceSelfDepthTexture = copy_description bb

; Dummy texture for resolution -------------

[ResourceViewportSize]
type = Texture2D

[CommandListPrepareViewportSize]
; Copy the info from the backbody so we match the resolution
ResourceViewportSize = copy_description bb

; Map display label ------------------------

[ResourceMapLabel_Valley4]
type = Buffer
data = "Invisible Walls: Valley 4"

[ResourceMapLabel_Wuling]
type = Buffer
data = "Invisible Walls: Wuling"

[ResourceMapLabelParams]
type = StructuredBuffer
array = 1
data = R32_FLOAT  +0.60 +0.65 +0.98 +0.70   1.00 0.20 0.20 1.00   0.00 0.00 0.00 0.90   0.01  0.01   2 2   0   1.3
;                x1-^  y1-^  x2-^  y2-^   | R-^  G-^  B-^  A-^  | R-^  G-^  B-^  A-^  | ^-H    V-^ | ^ ^ | ^ |  ^- font scale
;                Rectangle (range -1:+1)  | Text Color          | Background Color    | Border     |  ^  | ^- text alignment: 0=left 1=center 2=right
;                                         |                     |                     |            |  ^- h/v-anchor: 0=none 1=left/top 2=center 3=right/bottom 

[CommandListShowLabel]
if $wallMode == 1
	; Valley 4
	Resource\EFMIv1\Text = ref ResourceMapLabel_Valley4
else if $wallMode == 2
	; Wuling
	Resource\EFMIv1\Text = ref ResourceMapLabel_Wuling
endif
Resource\EFMIv1\TextParams = ref ResourceMapLabelParams
run = CommandList\EFMIv1\PrintText

; External resources -----------------------

[ResourceWallIB_Valley4]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = InvisWall\Mesh_Valley4_IB.buf

[ResourceWallVB_Valley4]
type = Buffer
stride = 20
filename = InvisWall\Mesh_Valley4_VB.buf

[ResourceWallIB_Wuling]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = InvisWall\Mesh_Wuling_IB.buf

[ResourceWallVB_Wuling]
type = Buffer
stride = 20
filename = InvisWall\Mesh_Wuling_VB.buf

; Render invisible walls -------------------

[CustomShaderInvisWalls]
vs = InvisWall\Shader_VS.hlsl
ps = InvisWall\Shader_PS.hlsl
hs = null
ds = null
gs = null

cull = front
topology = triangle_list
blend = ADD SRC_ALPHA INV_SRC_ALPHA

run = BuiltInCommandListUnbindAllRenderTargets
o0 = set_viewport bb

if $selfDepthTest == 1
	depth_enable = true
	depth_write_mask = all
	depth_func = greater_equal

	oD = ResourceSelfDepthTexture
	clear = ResourceSelfDepthTexture
endif

vs-cb0 = ref Resource\RCEFShaders\CameraCB->Region($\RCEFShaders\CameraCB_Offset, $\RCEFShaders\CameraCB_Size)
vs-cb1 = ref Resource\RCEFShaders\FrameCB->Region($\RCEFShaders\FrameCB_Offset, $\RCEFShaders\FrameCB_Size)
ps-t1 = Resource\RCEFShaders\SceneDepth
ps-t2 = ResourceViewportSize

if $wallMode == 1
	; Valley 4
	vb0 = ref ResourceWallVB_Valley4
	ib = ref ResourceWallIB_Valley4
	drawindexed = 36036, 0, 0
else if $wallMode == 2
	; Wuling
	vb0 = ref ResourceWallVB_Wuling
	ib = ref ResourceWallIB_Wuling
	drawindexed = 72144, 0, 0
endif

[Present]
$wallMode = $\RCEFShaders\ShowInvisWalls
$canRender = $\RCEFShaders\HasViewConstants == 1 && $\RCEFShaders\HasSceneDepth == 1
if $wallMode != 0 && $canRender == 1
	run = CommandListShowLabel

	if $selfDepthTest == 1
		run = CommandListPrepareSelfDepth
	endif

	run = CommandListPrepareViewportSize
	run = CustomShaderInvisWalls
endif