; Sub-Mod for RCEFShaders 1.5

; Feature Impl -----------------------------

[Constants]
; EXPERIMENTAL: Makes Invisible walls behind other invisible walls not render to avoid visual clutter.
; If enabling this, make sure to fill out the resWidth and resHeight with your game's resolution.
; Though it is recommended that you fill the resolution regardless of using this feature.
; To enable selfDepthTest, simply change the 0 to a 1
global $selfDepthTest = 0
global $resWidth = 1920
global $resHeight = 1080

global $wallMode = 0

; Depth mask for self depth test -----------

[ResourceWallDepth]
type = Texture2D
Width = $resWidth
height = $resHeight
format = DXGI_FORMAT_D32_FLOAT
array = 1
mips = 1
msaa = 1
bind_flags = depth_stencil

; Apparently, water has scene depth --------

[ResourceSceneDepth]

[ShaderOverrideWater]
hash = 4d4aeaba77c8835c
allow_duplicate_hash = true
ResourceSceneDepth = ref ps-t1

; External resources -----------------------

[ResourceWallIB_Valley4]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = InvisWall\Mesh_Valley4_IB.buf

[ResourceWallVB_Valley4]
type = Buffer
stride = 20
filename = InvisWall\Mesh_Valley4_VB.buf

[ResourceWallIB_Wuling]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = InvisWall\Mesh_Wuling_IB.buf

[ResourceWallVB_Wuling]
type = Buffer
stride = 20
filename = InvisWall\Mesh_Wuling_VB.buf

; Render invisible walls -------------------

[CustomShaderInvisWalls]
vs = InvisWall\Shader_VS.hlsl
ps = InvisWall\Shader_PS.hlsl
hs = null
ds = null
gs = null

topology = triangle_list
blend = ADD SRC_ALPHA INV_SRC_ALPHA

; Pass game res to IniParams[180].xy
x180 = res_width
y180 = res_height

if $selfDepthTest == 1
	depth_enable = true
	depth_write_mask = all
	depth_func = greater_equal
endif

run = BuiltInCommandListUnbindAllRenderTargets
o0 = set_viewport bb

if $selfDepthTest == 1
	oD = ResourceWallDepth
	clear = ResourceWallDepth
endif

if $wallMode == 1
	; Valley 4
	vb0 = ref ResourceWallVB_Valley4
	ib = ref ResourceWallIB_Valley4
else if $wallMode == 2
	; Wuling
	vb0 = ref ResourceWallVB_Wuling
	ib = ref ResourceWallIB_Wuling
endif

vs-cb0 = ref Resource\RCEFShaders\TerrainCB0->Region($\RCEFShaders\TerrainCB0_Offset, $\RCEFShaders\TerrainCB0_Size)
vs-cb1 = ref Resource\RCEFShaders\TerrainCB1->Region($\RCEFShaders\TerrainCB1_Offset, $\RCEFShaders\TerrainCB1_Size)
ps-t1 = ResourceSceneDepth

if $wallMode == 1
	; Valley 4
	drawindexed = 34812, 0, 0
else if $wallMode == 2
	; Wuling
	drawindexed = 71040, 0, 0
endif

[Present]
$wallMode = $\RCEFShaders\ShowInvisWalls
if $wallMode != 0 && $\RCEFShaders\TerrainSeen == 1
	run = CustomShaderInvisWalls
endif