; Feature Module of RCEFShaders

namespace = RCEFShaders\HideGameUI

; Feature Impl -----------------------------

[CommandListHideGameUI]
if $\EFMIv1\enable_mods && $\RCEFCore\HideGameUI
	handling = skip
endif

[ShaderOverride_01259601012f89c3]
hash = 01259601012f89c3
allow_duplicate_hash = true
run = CommandListHideGameUI

[ShaderOverride_0455377ec18d59bc]
hash = 0455377ec18d59bc
allow_duplicate_hash = true
run = CommandListHideGameUI

[ShaderOverride_524a724a453fd672]
hash = 524a724a453fd672
allow_duplicate_hash = true
run = CommandListHideGameUI

[ShaderOverride_54f066aab750db23]
hash = 54f066aab750db23
allow_duplicate_hash = true
run = CommandListHideGameUI

[ShaderOverride_bc279606858d5235]
hash = bc279606858d5235
allow_duplicate_hash = true
run = CommandListHideGameUI

[ShaderOverride_f2dc00276bab2d84]
hash = f2dc00276bab2d84
allow_duplicate_hash = true
run = CommandListHideGameUI

[ShaderOverride_7983dd7b33f4a115]
hash = 7983dd7b33f4a115
allow_duplicate_hash = true
run = CommandListHideGameUI

[ShaderOverride_8241579e34ea6fc2]
hash = 8241579e34ea6fc2
allow_duplicate_hash = true
run = CommandListHideGameUI

[ShaderOverride_31e6daaf8342d9b6]
hash = 31e6daaf8342d9b6
allow_duplicate_hash = true
run = CommandListHideGameUI

[ShaderOverride_dae7c6cdd8a78d51]
hash = dae7c6cdd8a78d51
allow_duplicate_hash = true
run = CommandListHideGameUI

[ShaderOverride_ee9c85fadead6f7a]
hash = ee9c85fadead6f7a
allow_duplicate_hash = true
run = CommandListHideGameUI

[ShaderOverride_859100cba35137a1]
hash = 859100cba35137a1
allow_duplicate_hash = true
run = CommandListHideGameUI