; Feature Module of RCEFShaders

namespace = RCEFCore\UnlitView

; Feature Impl -----------------------------

[ShaderOverride_Bloom01]
hash = fea5ae37baee4633
allow_duplicate_hash = true
if $\EFMIv1\enable_mods && $\RCEFCore\UnlitView
	handling = skip
endif

[ShaderOverride_VolumetricFog01]
hash = 5bffbe3f9080ee1b
allow_duplicate_hash = true
if $\EFMIv1\enable_mods && $\RCEFCore\UnlitView
	handling = skip
endif

[ShaderOverride_VolumetricFog02]
hash = a9df465769d2999b
allow_duplicate_hash = true
if $\EFMIv1\enable_mods && $\RCEFCore\UnlitView
	handling = skip
endif

[ShaderOverride_SnowForestMisdirect01]
hash = 8d963a73ac6a388e
allow_duplicate_hash = true
if $\EFMIv1\enable_mods && $\RCEFCore\UnlitView
	handling = skip
endif


[CustomShader_4d4aeaba77c8835c]
ps = Shaders\4d4aeaba77c8835c.hlsl
draw = from_caller

[ShaderOverride_4d4aeaba77c8835c]
hash = 4d4aeaba77c8835c
allow_duplicate_hash = true
if $\EFMIv1\enable_mods && $\RCEFCore\UnlitView
	handling = skip
	run = CustomShader_4d4aeaba77c8835c
endif


[CustomShader_743f991c236b6dde]
ps = Shaders\Terrain\743f991c236b6dde.hlsl
draw = from_caller

[ShaderOverride_743f991c236b6dde]
hash = 743f991c236b6dde
allow_duplicate_hash = true
if $\EFMIv1\enable_mods && $\RCEFCore\UnlitView
	handling = skip
	run = CustomShader_743f991c236b6dde
endif


[CustomShader_b8360398f113f945]
ps = Shaders\Terrain\b8360398f113f945.hlsl
draw = from_caller

[ShaderOverride_b8360398f113f945]
hash = b8360398f113f945
allow_duplicate_hash = true
if $\EFMIv1\enable_mods && $\RCEFCore\UnlitView
	handling = skip
	run = CustomShader_b8360398f113f945
endif


[CustomShader_30462d509b56535f]
ps = Shaders\Terrain\30462d509b56535f.hlsl
draw = from_caller

[ShaderOverride_30462d509b56535f]
hash = 30462d509b56535f
allow_duplicate_hash = true
if $\EFMIv1\enable_mods && $\RCEFCore\UnlitView
	handling = skip
	run = CustomShader_30462d509b56535f
endif


[CustomShader_addb4925f6e279b8]
ps = Shaders\Terrain\addb4925f6e279b8.hlsl
draw = from_caller

[ShaderOverride_addb4925f6e279b8]
hash = addb4925f6e279b8
allow_duplicate_hash = true
if $\EFMIv1\enable_mods && $\RCEFCore\UnlitView
	handling = skip
	run = CustomShader_addb4925f6e279b8
endif


[CustomShader_955aa6eb61756d0c]
ps = Shaders\Terrain\955aa6eb61756d0c.hlsl
draw = from_caller

[ShaderOverride_955aa6eb61756d0c]
hash = 955aa6eb61756d0c
allow_duplicate_hash = true
if $\EFMIv1\enable_mods && $\RCEFCore\UnlitView
	handling = skip
	run = CustomShader_955aa6eb61756d0c
endif


[CustomShader_17b280fb09bf16fd]
ps = Shaders\Terrain\17b280fb09bf16fd.hlsl
draw = from_caller

[ShaderOverride_17b280fb09bf16fd]
hash = 17b280fb09bf16fd
allow_duplicate_hash = true
if $\EFMIv1\enable_mods && $\RCEFCore\UnlitView
	handling = skip
	run = CustomShader_17b280fb09bf16fd
endif


[CustomShader_530cf926c33e99ee]
ps = Shaders\Terrain\530cf926c33e99ee.hlsl
draw = from_caller

[ShaderOverride_530cf926c33e99ee]
hash = 530cf926c33e99ee
allow_duplicate_hash = true
if $\EFMIv1\enable_mods && $\RCEFCore\UnlitView
	handling = skip
	run = CustomShader_530cf926c33e99ee
endif


[CustomShader_bb9293bfbf23a3c5]
ps = Shaders\Terrain\bb9293bfbf23a3c5.hlsl
draw = from_caller

[ShaderOverride_bb9293bfbf23a3c5]
hash = bb9293bfbf23a3c5
allow_duplicate_hash = true
if $\EFMIv1\enable_mods && $\RCEFCore\UnlitView
	handling = skip
	run = CustomShader_bb9293bfbf23a3c5
endif


[CustomShader_5e5271b322c7bd5c]
ps = Shaders\Terrain\5e5271b322c7bd5c.hlsl
draw = from_caller

[ShaderOverride_5e5271b322c7bd5c]
hash = 5e5271b322c7bd5c
allow_duplicate_hash = true
if $\EFMIv1\enable_mods && $\RCEFCore\UnlitView
	handling = skip
	run = CustomShader_5e5271b322c7bd5c
endif


[CustomShader_6f33660185243d05]
ps = Shaders\Terrain\6f33660185243d05.hlsl
draw = from_caller

[ShaderOverride_6f33660185243d05]
hash = 6f33660185243d05
allow_duplicate_hash = true
if $\EFMIv1\enable_mods && $\RCEFCore\UnlitView
	handling = skip
	run = CustomShader_6f33660185243d05
endif


[CustomShader_37eacbc3c84bb392]
ps = Shaders\Terrain\37eacbc3c84bb392.hlsl
draw = from_caller

[ShaderOverride_37eacbc3c84bb392]
hash = 37eacbc3c84bb392
allow_duplicate_hash = true
if $\EFMIv1\enable_mods && $\RCEFCore\UnlitView
	handling = skip
	run = CustomShader_37eacbc3c84bb392
endif


[CustomShader_e5c79df0d5b00481]
ps = Shaders\Terrain\e5c79df0d5b00481.hlsl
draw = from_caller

[ShaderOverride_e5c79df0d5b00481]
hash = e5c79df0d5b00481
allow_duplicate_hash = true
if $\EFMIv1\enable_mods && $\RCEFCore\UnlitView
	handling = skip
	run = CustomShader_e5c79df0d5b00481
endif


[CustomShader_44719138df0a512b]
ps = Shaders\Terrain\44719138df0a512b.hlsl
draw = from_caller

[ShaderOverride_44719138df0a512b]
hash = 44719138df0a512b
allow_duplicate_hash = true
if $\EFMIv1\enable_mods && $\RCEFCore\UnlitView
	handling = skip
	run = CustomShader_44719138df0a512b
endif


[CustomShader_2fd35c280da6db61]
ps = Shaders\Terrain\2fd35c280da6db61.hlsl
draw = from_caller

[ShaderOverride_2fd35c280da6db61]
hash = 2fd35c280da6db61
allow_duplicate_hash = true
if $\EFMIv1\enable_mods && $\RCEFCore\UnlitView
	handling = skip
	run = CustomShader_2fd35c280da6db61
endif


[CustomShader_d6cd817025f6567c]
ps = Shaders\Terrain\d6cd817025f6567c.hlsl
draw = from_caller

[ShaderOverride_d6cd817025f6567c]
hash = d6cd817025f6567c
allow_duplicate_hash = true
if $\EFMIv1\enable_mods && $\RCEFCore\UnlitView
	handling = skip
	run = CustomShader_d6cd817025f6567c
endif


[CustomShader_512cc3b9be7a6ae0]
ps = Shaders\Terrain\512cc3b9be7a6ae0.hlsl
draw = from_caller

[ShaderOverride_512cc3b9be7a6ae0]
hash = 512cc3b9be7a6ae0
allow_duplicate_hash = true
if $\EFMIv1\enable_mods && $\RCEFCore\UnlitView
	handling = skip
	run = CustomShader_512cc3b9be7a6ae0
endif


[CustomShader_e02f4d6993f80551]
ps = Shaders\Foliage\e02f4d6993f80551.hlsl
draw = from_caller

[ShaderOverride_e02f4d6993f80551]
hash = e02f4d6993f80551
allow_duplicate_hash = true
if $\EFMIv1\enable_mods && $\RCEFCore\UnlitView
	handling = skip
	run = CustomShader_e02f4d6993f80551
endif


[CustomShader_c2f0f0165b78a730]
ps = Shaders\Foliage\c2f0f0165b78a730.hlsl
draw = from_caller

[ShaderOverride_c2f0f0165b78a730]
hash = c2f0f0165b78a730
allow_duplicate_hash = true
if $\EFMIv1\enable_mods && $\RCEFCore\UnlitView
	handling = skip
	run = CustomShader_c2f0f0165b78a730
endif


[CustomShader_b564381e16bd84f4]
ps = Shaders\Foliage\b564381e16bd84f4.hlsl
draw = from_caller

[ShaderOverride_b564381e16bd84f4]
hash = b564381e16bd84f4
allow_duplicate_hash = true
if $\EFMIv1\enable_mods && $\RCEFCore\UnlitView
	handling = skip
	run = CustomShader_b564381e16bd84f4
endif


[CustomShader_2c0a0efb51eb7e5b]
ps = Shaders\Foliage\2c0a0efb51eb7e5b.hlsl
draw = from_caller

[ShaderOverride_2c0a0efb51eb7e5b]
hash = 2c0a0efb51eb7e5b
allow_duplicate_hash = true
if $\EFMIv1\enable_mods && $\RCEFCore\UnlitView
	handling = skip
	run = CustomShader_2c0a0efb51eb7e5b
endif


[CustomShader_a990d7a6eca08f04]
ps = Shaders\Foliage\a990d7a6eca08f04.hlsl
draw = from_caller

[ShaderOverride_a990d7a6eca08f04]
hash = a990d7a6eca08f04
allow_duplicate_hash = true
if $\EFMIv1\enable_mods && $\RCEFCore\UnlitView
	handling = skip
	run = CustomShader_a990d7a6eca08f04
endif


[CustomShader_3130bda32c0d1261]
ps = Shaders\Foliage\3130bda32c0d1261.hlsl
draw = from_caller

[ShaderOverride_3130bda32c0d1261]
hash = 3130bda32c0d1261
allow_duplicate_hash = true
if $\EFMIv1\enable_mods && $\RCEFCore\UnlitView
	handling = skip
	run = CustomShader_3130bda32c0d1261
endif


[CustomShader_b142c026a459d8c6]
ps = Shaders\Foliage\b142c026a459d8c6.hlsl
draw = from_caller

[ShaderOverride_b142c026a459d8c6]
hash = b142c026a459d8c6
allow_duplicate_hash = true
if $\EFMIv1\enable_mods && $\RCEFCore\UnlitView
	handling = skip
	run = CustomShader_b142c026a459d8c6
endif


[CustomShader_4009fb12d319f84c]
ps = Shaders\Foliage\4009fb12d319f84c.hlsl
draw = from_caller

[ShaderOverride_4009fb12d319f84c]
hash = 4009fb12d319f84c
allow_duplicate_hash = true
if $\EFMIv1\enable_mods && $\RCEFCore\UnlitView
	handling = skip
	run = CustomShader_4009fb12d319f84c
endif