; Still a little finnicky to be part of RCEFShaders

namespace = RCEFShaders\HideUID

; Feature Impl -----------------------------

[Constants]
global $IsMainMenu = 0
global $IsLoadingScreen = 0

global $InPauseMenu = 0
global $DetectPauseMenu1 = 0
global $DetectPauseMenu2 = 0
global $DetectPauseMenu3 = 0

global $InProfileMenu = 0
global $DetectProfileMenu1 = 0
global $DetectProfileMenu2 = 0
global $DetectProfileMenu3 = 0
global $DetectNotProfileMenu = 0

; Add a gate here if you don't want this always active
[CommandListHideUID]
handling = skip

; Detection --------------------------------

[ShaderOverride_MainMenu]
hash = c1d9f51e6a8a77a7
$IsMainMenu = 1

[TextureOverride_LoadingScreen]
hash = 0a1d9543
match_first_index = 66
match_index_count = 2694
$IsLoadingScreen = 1

[TextureOverride_DetectPause_1]
hash = d3609291
match_first_index = 0
match_index_count = 150
$DetectPauseMenu1 = 1

[TextureOverride_DetectPause_2]
hash = 1b29e1e6
match_first_index = 168
match_index_count = 12
$DetectPauseMenu2 = 1

[TextureOverride_DetectPause_3]
hash = cbe01d4c
match_first_index = 306
match_index_count = 6
$DetectPauseMenu3 = 1

[TextureOverride_DetectProfile_1]
hash = cbe01d4c
match_index_count = 6
if first_index == 240 || first_index == 294 || first_index == 28278
	$DetectProfileMenu1 = 1
endif

[TextureOverride_DetectProfile_2]
hash = efa96139
match_index_count = 168
$DetectProfileMenu2 = 1

[TextureOverride_DetectProfile_3]
hash = 8dd45a15
match_index_count = 18
$DetectProfileMenu3 = 1

[TextureOverride_DetectNotProfile_1]
hash = 4f69e6b3
match_index_count = 114
if first_index == 444 || first_index == 498
	$DetectNotProfileMenu = 1
endif

[TextureOverride_DetectNotProfile_2]
hash = 3de0936b
match_index_count = 210
if first_index == 510 || first_index == 564
	$DetectNotProfileMenu = 1
endif

[Present]
if !$IsMainMenu && !$IsLoadingScreen && !$\RCEFCore\InGameWorld
	$InPauseMenu = $DetectPauseMenu1 || $DetectPauseMenu2 || $DetectPauseMenu3
	post $DetectPauseMenu1 = 0
	post $DetectPauseMenu2 = 0
	post $DetectPauseMenu3 = 0
	
	$InProfileMenu = !$DetectNotProfileMenu && ($DetectProfileMenu1 || $DetectProfileMenu2 || $DetectProfileMenu3)
	post $DetectProfileMenu1 = 0
	post $DetectProfileMenu2 = 0
	post $DetectProfileMenu3 = 0
	post $DetectNotProfileMenu = 0
else
	$InPauseMenu = 0
	$InProfileMenu = 0
	post $IsMainMenu = 0
	post $IsLoadingScreen = 0
endif

; Hide Menu UID ----------------------------

[TextureOverride_PauseUID]
hash = 1ad9c553
match_index_count = 108
if $InPauseMenu && (first_index == 1728 || first_index == 1734 || first_index == 1740 || first_index == 1746)
	run = CommandListHideUID
endif

[TextureOverride_ProfileName]
hash = c0cb916b
match_index_count = 102
if $InProfileMenu
	run = CommandListHideUID
endif

[TextureOverride_ProfileUID]
hash = a34f201c
match_index_count = 66
if $InProfileMenu && first_index != 396 && first_index != 28452
	run = CommandListHideUID
endif

; Hide Corner UID --------------------------

[TextureOverride_CornerUID]
hash = 4f69e6b3
match_index_count = 114
if first_index == 18
	run = CommandListHideUID
endif