; For ENDFIELD 1.5

namespace = RCEFShaders

; Values -----------------------------------

[Constants]
global $ShowKeyInfo = 0
global $FullAICRegions = 0
global $FullAICTiles = 0

global $UnlitView = 0
global $HideFoliage = 0
global $HideGameUI = 0

global $ShowCamCoords = 0
global $ShowInvisWalls = 0

; Keybinds ---------------------------------

[KeyShowKeyInfo]
key = VK_MENU VK_END
type = cycle
$ShowKeyInfo = 0, 1

[KeyFullAICRegions]
key = VK_MENU VK_NUMPAD1
type = cycle
$FullAICRegions = 0, 1

[KeyFullAICTiles]
key = VK_MENU VK_NUMPAD2
type = cycle
$FullAICTiles = 0, 1

[KeyUnlitView]
key = VK_MENU VK_NUMPAD4
type = cycle
$UnlitView = 0, 1

[KeyHideFoliage]
key = VK_MENU VK_NUMPAD5
type = cycle
$HideFoliage = 0, 1

[KeyHideGameUI]
key = VK_MENU VK_NUMPAD6
type = cycle
$HideGameUI = 0, 1

[KeyShowCamCoords]
key = VK_MENU VK_NUMPAD7
type = cycle
$ShowCamCoords = 0, 1

[KeyShowInvisWalls]
key = VK_MENU VK_NUMPAD8
type = cycle
$ShowInvisWalls = 0, 1, 2

; Default Keybinds Screen ------------------

[ResourceKeyInfoText]
type = buffer
format = R8_UINT
filename = KeyInfo.txt

[ResourceKeyInfoParams]
type = StructuredBuffer
array = 1
data = R32_FLOAT  -0.50 +0.50 +0.50 -0.50   1.00 0.70 0.20 1.00   0.00 0.00 0.00 0.75   0.01  0.01   2 2   0   1.2
;                x1-^  y1-^  x2-^  y2-^   | R-^  G-^  B-^  A-^  | R-^  G-^  B-^  A-^  | ^-H    V-^ | ^ ^ | ^ |  ^- font scale
;                Rectangle (range -1:+1)  | Text Color          | Background Color    | Border     |  ^  | ^- text alignment: 0=left 1=center 2=right
;                                         |                     |                     |            |  ^- h/v-anchor: 0=none 1=left/top 2=center 3=right/bottom 

[CommandListKeyInfo]
Resource\EFMIv1\Text = ref ResourceKeyInfoText
Resource\EFMIv1\TextParams = ref ResourceKeyInfoParams
run = CommandList\EFMIv1\PrintText

[Present]
if $ShowKeyInfo == 1
	run = CommandListKeyInfo
endif