; Library for RCEFShaders 1.5

namespace = RCEFShaders

[Constants]
global $TerrainSeen = 0

global $TerrainCB0_Offset = 0
global $TerrainCB0_Size = 0

global $TerrainCB1_Offset = 0
global $TerrainCB1_Size = 0

; View/Camera Constants
[ResourceTerrainCB0]

; Frame/Screen Constants
[ResourceTerrainCB1]

; Implementation ---------------------------

[Present]
post $TerrainSeen = 0

[CommandListTerrainCapture]
$TerrainCB0_Offset = vs-CB0->Offset
$TerrainCB0_Size = vs-CB0->Size
ResourceTerrainCB0 = ref vs-CB0

$TerrainCB1_Offset = vs-CB1->Offset
$TerrainCB1_Size = vs-CB1->Size
ResourceTerrainCB1 = ref vs-CB1

$TerrainSeen = 1

[ShaderOverrideTerrain]
hash = 5204669b553b0cda
allow_duplicate_hash = true
run = CommandListTerrainCapture