; Feature Module of RCEFShaders

namespace = RCEFShaders\Coordinates

; Feature Impl -----------------------------

[Constants]
global persist $AnchorCenterX = 0.84
global persist $AnchorTopY = 0.09
global $AnchorSizeX = 0.05
global $AnchorSizeY = 0.02

; DO NOT configure these
global $IsDragging = 0
global $CanDrag = 0

[KeyDragMenu]
condition = $\RCEFCore\Coordinates && $CanDrag
key = VK_LBUTTON
type = hold
$IsDragging = 1

[Present]
if $\RCEFCore\Coordinates && $\RCEFLibrary\HasViewConstants && $\RCEFLibrary\HasValidViewport

	local $DragMinX = $AnchorCenterX - ($AnchorSizeX / 2)
	local $DragMaxX = $DragMinX + $AnchorSizeX
	local $DragMaxY = $AnchorTopY + ($AnchorSizeY * $\RCEFLibrary\AspectRatio)
	$CanDrag = cursor_x >= $DragMinX && cursor_x <= $DragMaxX && cursor_y >= $AnchorTopY && cursor_y <= $DragMaxY
	if $IsDragging
		$AnchorCenterX = cursor_x
		$AnchorTopY = cursor_y

		local $HalfWidth = $AnchorSizeX / 2
		local $AnchorHeight = $AnchorSizeY * $\RCEFLibrary\AspectRatio

		if $AnchorCenterX < $HalfWidth
			$AnchorCenterX = $HalfWidth
		elif $AnchorCenterX > 1 - $HalfWidth
			$AnchorCenterX = 1 - $HalfWidth
		endif
		
		if $AnchorTopY < 0
			$AnchorTopY = 0
		elif $AnchorTopY > 1 - $AnchorHeight
			$AnchorTopY = 1 - $AnchorHeight
		endif
	endif

	local $savedX99 = x99
	local $savedY99 = y99
	local $savedZ99 = z99
	local $savedW99 = w99

	run = CustomShaderDrawAnchor
	run = CustomShaderWriteCoords
	run = CommandListDrawCoords

	x99 = $savedX99
	y99 = $savedY99
	z99 = $savedZ99
	w99 = $savedW99
endif

[ResourceCoordText]
type = RWBuffer
format = R8_UINT
array = 128

[CustomShaderDrawAnchor]
vs = ..\..\Core\Shaders\Draw2D.hlsl
ps = ..\..\Core\Shaders\Draw2D.hlsl
cs = null
ds = null
gs = null
hs = null
cull = none
topology = triangle_strip
blend = ADD SRC_ALPHA INV_SRC_ALPHA
o0 = set_viewport no_view_cache bb
x99 = $AnchorCenterX - ($AnchorSizeX / 2)
y99 = $AnchorTopY
z99 = $AnchorSizeX
w99 = $AnchorSizeY * $\RCEFLibrary\AspectRatio
ps-cb0 = ref Resource\RCEFMenu\ColorYellow
ps-t1 = null
draw = 4, 0
ps-cb0 = null

[CustomShaderWriteCoords]
cs = WriteCoords.hlsl
cs-cb0 = ref Resource\RCEFLibrary\PlayerCB
cs-u0 = ResourceCoordText
dispatch = 1, 1, 1
cs-u0 = null
cs-cb0 = null

[CommandListDrawCoords]
z99 = 1
w99 = 1.7
x99 = $AnchorCenterX
y99 = $AnchorTopY + ($AnchorSizeY * $\RCEFLibrary\AspectRatio / 2) - ($\RCEFText\TexelSize * w99 / 2)
Resource\RCEFText\Text = ref ResourceCoordText
Resource\RCEFText\BackColor = ref Resource\RCEFMenu\ColorBlack
Resource\RCEFText\TextColor = ref Resource\RCEFMenu\ColorYellow
run = CommandList\RCEFText\PrintText