; Feature Module of RCEFShaders

namespace = RCEFShaders\SolidAIC

; Feature Impl -----------------------------

[CustomShaderAICRegion]
ps = Shaders\5eacc3f1e20a6e04.hlsl
draw = from_caller

[ShaderOverrideAICRegion]
hash = 5eacc3f1e20a6e04
allow_duplicate_hash = true
if $\RCEFCore\SolidAICRegion
	handling = skip
	run = CustomShaderAICRegion
endif

[CustomShaderAICTiles]
ps = Shaders\700e02fb213abdcf.hlsl
draw = from_caller

[ShaderOverrideAICTiles]
hash = 700e02fb213abdcf
allow_duplicate_hash = true
if $\RCEFCore\SolidAICTiles
	handling = skip
	run = CustomShaderAICTiles
endif