; Foilage Culling Menu Section of RCEFShaders

namespace = RCEFMenu\Foliage

[Constants]
global $MinY = 0
global $MaxY = 0

global $MinX_Off = 0
global $MaxX_Off = 0

global $MinX_All = 0
global $MaxX_All = 0

global $MinX_Prox = 0
global $MaxX_Prox = 0

[KeySelectMode]
key = VK_LBUTTON
run = CommandListMakeSelection

[CommandListMakeSelection]
if cursor_y >= $MinY && cursor_y <= $MaxY
	if cursor_x >= $MinX_Off && cursor_x <= $MaxX_Off
		$\RCEFCore\FoliageMode = 0
	elif cursor_x >= $MinX_All && cursor_x <= $MaxX_All
		$\RCEFCore\FoliageMode = 1
	elif cursor_x >= $MinX_Prox && cursor_x <= $MaxX_Prox
		$\RCEFCore\FoliageMode = 2
	endif
endif

[ResourceSectionHeader]
type = Buffer
format = R8_UINT
data = "Foliage Culling"

[ResourceOptionOff]
type = Buffer
format = R8_UINT
data = "Off"

[ResourceOptionAll]
type = Buffer
format = R8_UINT
data = "All"

[ResourceOptionProximity]
type = Buffer
format = R8_UINT
data = "Proximity"

[CommandListDrawSection]
local $OffsetX = $\RCEFMenu\PanelPosX + ($\RCEFMenu\AnchorSizeX / 2)

x99 = $OffsetX
y99 = $\RCEFMenu\OffsetY
z99 = 0
w99 = 1.6
Resource\RCEFText\Text = ref ResourceSectionHeader
run = CommandList\RCEFMenu\DrawNormalText

$\RCEFMenu\OffsetY = $\RCEFMenu\OffsetY + ($\RCEFText\TexelSize * w99) + ($\RCEFMenu\PaddingY * $\RCEFLibrary\AspectRatio)

$MinY = $\RCEFMenu\OffsetY
$MaxY = $MinY + $\RCEFText\TexelSize * w99
$OffsetX = $\RCEFMenu\PanelPosX + $\RCEFMenu\AnchorSizeX

x99 = $OffsetX
y99 = $\RCEFMenu\OffsetY
w99 = 1.5
Resource\RCEFText\Text = ref ResourceOptionOff
if $\RCEFCore\FoliageMode == 0
	run = CommandList\RCEFMenu\DrawSelectedText
else
	run = CommandList\RCEFMenu\DrawNormalText
endif

$OffsetX = $OffsetX + (3 * $\RCEFText\TexelSize * $\RCEFText\WidthMulti * w99 / $\RCEFLibrary\AspectRatio)

$MinX_Off = x99
$MaxX_Off = $OffsetX

$OffsetX = $OffsetX + $\RCEFMenu\PaddingX

x99 = $OffsetX
Resource\RCEFText\Text = ref ResourceOptionAll
if $\RCEFCore\FoliageMode == 1
	run = CommandList\RCEFMenu\DrawSelectedText
else
	run = CommandList\RCEFMenu\DrawNormalText
endif

$OffsetX = $OffsetX + (3 * $\RCEFText\TexelSize * $\RCEFText\WidthMulti * w99 / $\RCEFLibrary\AspectRatio)

$MinX_All = x99
$MaxX_All = $OffsetX

$OffsetX = $OffsetX + $\RCEFMenu\PaddingX

x99 = $OffsetX
Resource\RCEFText\Text = ref ResourceOptionProximity
if $\RCEFCore\FoliageMode == 2
	run = CommandList\RCEFMenu\DrawSelectedText
else
	run = CommandList\RCEFMenu\DrawNormalText
endif

$OffsetX = $OffsetX + (9 * $\RCEFText\TexelSize * $\RCEFText\WidthMulti * w99 / $\RCEFLibrary\AspectRatio)

$MinX_Prox = x99
$MaxX_Prox = $OffsetX

$\RCEFMenu\OffsetY = $\RCEFMenu\OffsetY + ($\RCEFText\TexelSize * w99) + ($\RCEFMenu\PaddingY * $\RCEFLibrary\AspectRatio)