; Invisible Wall Menu Section of RCEFShaders

namespace = RCEFMenu\InvisWalls

[Constants]
global $MinY = 0
global $MaxY = 0

global $MinX_Off = 0
global $MaxX_Off = 0

global $MinX_Valley4 = 0
global $MaxX_Valley4 = 0

global $MinX_Wuling = 0
global $MaxX_Wuling = 0

[KeySelectMode]
key = VK_LBUTTON
run = CommandListMakeSelection

[CommandListMakeSelection]
if cursor_y >= $MinY && cursor_y <= $MaxY
	if cursor_x >= $MinX_Off && cursor_x <= $MaxX_Off
		$\RCEFCore\InvisWallMode = 0
	elif cursor_x >= $MinX_Valley4 && cursor_x <= $MaxX_Valley4
		$\RCEFCore\InvisWallMode = 1
	elif cursor_x >= $MinX_Wuling && cursor_x <= $MaxX_Wuling
		$\RCEFCore\InvisWallMode = 2
	endif
endif

[ResourceSectionHeader]
type = Buffer
format = R8_UINT
data = "Invisible Walls"

[ResourceOptionOff]
type = Buffer
format = R8_UINT
data = "Off"

[ResourceOptionValley4]
type = Buffer
format = R8_UINT
data = "Valley-4"

[ResourceOptionWuling]
type = Buffer
format = R8_UINT
data = "Wuling"

[CommandListDrawSection]
local $OffsetX = $\RCEFMenu\PanelPosX + ($\RCEFMenu\AnchorSizeX / 2)

x99 = $OffsetX
y99 = $\RCEFMenu\OffsetY
z99 = 0
w99 = 1.6
Resource\RCEFText\Text = ref ResourceSectionHeader
run = CommandList\RCEFMenu\DrawNormalText

$\RCEFMenu\OffsetY = $\RCEFMenu\OffsetY + ($\RCEFText\TexelSize * w99) + ($\RCEFMenu\PaddingY * $\RCEFMenu\AspectRatio)

$MinY = $\RCEFMenu\OffsetY
$MaxY = $MinY + $\RCEFText\TexelSize * w99
$OffsetX = $\RCEFMenu\PanelPosX + $\RCEFMenu\AnchorSizeX

x99 = $OffsetX
y99 = $\RCEFMenu\OffsetY
w99 = 1.5
Resource\RCEFText\Text = ref ResourceOptionOff
if $\RCEFCore\InvisWallMode == 0
	run = CommandList\RCEFMenu\DrawSelectedText
else
	run = CommandList\RCEFMenu\DrawNormalText
endif

$OffsetX = $OffsetX + (3 * $\RCEFText\TexelSize * $\RCEFText\WidthMulti * w99 / $\RCEFMenu\AspectRatio)

$MinX_Off = x99
$MaxX_Off = $OffsetX

$OffsetX = $OffsetX + $\RCEFMenu\PaddingX

x99 = $OffsetX
Resource\RCEFText\Text = ref ResourceOptionValley4
if $\RCEFCore\InvisWallMode == 1
	run = CommandList\RCEFMenu\DrawSelectedText
else
	run = CommandList\RCEFMenu\DrawNormalText
endif

$OffsetX = $OffsetX + (9 * $\RCEFText\TexelSize * $\RCEFText\WidthMulti * w99 / $\RCEFMenu\AspectRatio)

$MinX_Valley4 = x99
$MaxX_Valley4 = $OffsetX

$OffsetX = $OffsetX + $\RCEFMenu\PaddingX * 0.5

x99 = $OffsetX
Resource\RCEFText\Text = ref ResourceOptionWuling
if $\RCEFCore\InvisWallMode == 2
	run = CommandList\RCEFMenu\DrawSelectedText
else
	run = CommandList\RCEFMenu\DrawNormalText
endif

$OffsetX = $OffsetX + (6 * $\RCEFText\TexelSize * $\RCEFText\WidthMulti * w99 / $\RCEFMenu\AspectRatio)

$MinX_Wuling = x99
$MaxX_Wuling = $OffsetX

$\RCEFMenu\OffsetY = $\RCEFMenu\OffsetY + ($\RCEFText\TexelSize * w99) + ($\RCEFMenu\PaddingY * $\RCEFMenu\AspectRatio)