; Map Type Menu Section of RCEFShaders

namespace = RCEFMenu\MapType

[Constants]
global $MinY = 0
global $MaxY = 0

global $MinX_Valley4 = 0
global $MaxX_Valley4 = 0

global $MinX_Wuling = 0
global $MaxX_Wuling = 0

[KeySelectMode]
condition = $\RCEFMenu\IsOpen
key = VK_LBUTTON
run = CommandListMakeSelection

[CommandListMakeSelection]
if cursor_y >= $MinY && cursor_y <= $MaxY
	if cursor_x >= $MinX_Valley4 && cursor_x <= $MaxX_Valley4
		$\RCEFCore\ActiveScene = 0
	elif cursor_x >= $MinX_Wuling && cursor_x <= $MaxX_Wuling
		$\RCEFCore\ActiveScene = 1
	endif
endif

[ResourceSectionHeader]
type = Buffer
format = R8_UINT
data = "Active Scene"

[ResourceOptionValley4]
type = Buffer
format = R8_UINT
data = "Valley-4"

[ResourceOptionWuling]
type = Buffer
format = R8_UINT
data = "Wuling"

[CommandListDrawSection]
local $OffsetX = $\RCEFMenu\PanelPosX + ($\RCEFMenu\AnchorSizeX / 2)

x99 = $OffsetX
y99 = $\RCEFMenu\OffsetY
z99 = 0
w99 = 1.6
Resource\RCEFText\Text = ref ResourceSectionHeader
run = CommandList\RCEFMenu\DrawNormalText

$\RCEFMenu\OffsetY = $\RCEFMenu\OffsetY + ($\RCEFText\TexelSize * w99) + ($\RCEFMenu\PaddingY * $\RCEFLibrary\AspectRatio)

$MinY = $\RCEFMenu\OffsetY
$MaxY = $MinY + $\RCEFText\TexelSize * w99
$OffsetX = $\RCEFMenu\PanelPosX + $\RCEFMenu\AnchorSizeX

x99 = $OffsetX
y99 = $\RCEFMenu\OffsetY
w99 = 1.5
Resource\RCEFText\Text = ref ResourceOptionValley4
if $\RCEFCore\ActiveScene == 0
	run = CommandList\RCEFMenu\DrawSelectedText
else
	run = CommandList\RCEFMenu\DrawNormalText
endif

$OffsetX = $OffsetX + (9 * $\RCEFText\TexelSize * $\RCEFText\WidthMulti * w99 / $\RCEFLibrary\AspectRatio)

$MinX_Valley4 = x99
$MaxX_Valley4 = $OffsetX

$OffsetX = $OffsetX + $\RCEFMenu\PaddingX * 0.5

x99 = $OffsetX
Resource\RCEFText\Text = ref ResourceOptionWuling
if $\RCEFCore\ActiveScene == 1
	run = CommandList\RCEFMenu\DrawSelectedText
else
	run = CommandList\RCEFMenu\DrawNormalText
endif

$OffsetX = $OffsetX + (6 * $\RCEFText\TexelSize * $\RCEFText\WidthMulti * w99 / $\RCEFLibrary\AspectRatio)

$MinX_Wuling = x99
$MaxX_Wuling = $OffsetX

$\RCEFMenu\OffsetY = $\RCEFMenu\OffsetY + ($\RCEFText\TexelSize * w99) + ($\RCEFMenu\PaddingY * $\RCEFLibrary\AspectRatio)