; Misc Menu Section of RCEFShaders

namespace = RCEFMenu\Misc

[Constants]
global $MinY = 0
global $MaxY = 0

global $MinX_Unlit = 0
global $MaxX_Unlit = 0

global $MinX_HideUI = 0
global $MaxX_HideUI = 0

global $MinX_CamCoords = 0
global $MaxX_CamCoords = 0

[KeySelectMode]
key = VK_LBUTTON
run = CommandListMakeSelection

[CommandListMakeSelection]
if cursor_y >= $MinY && cursor_y <= $MaxY
	if cursor_x >= $MinX_Unlit && cursor_x <= $MaxX_Unlit
		$\RCEFCore\UnlitView = !$\RCEFCore\UnlitView
	elif cursor_x >= $MinX_HideUI && cursor_x <= $MaxX_HideUI
		$\RCEFCore\HideGameUI = !$\RCEFCore\HideGameUI
	elif cursor_x >= $MinX_CamCoords && cursor_x <= $MaxX_CamCoords
		$\RCEFCore\CamCoords = !$\RCEFCore\CamCoords
	endif
endif

[ResourceSectionHeader]
type = Buffer
format = R8_UINT
data = "Misc"

[ResourceOptionUnlit]
type = Buffer
format = R8_UINT
data = "Unlit"

[ResourceOptionHideUI]
type = Buffer
format = R8_UINT
data = "HideUI"

[ResourceOptionCamCoords]
type = Buffer
format = R8_UINT
data = "CamCoords"

[CommandListDrawSection]
local $OffsetX = $\RCEFMenu\PanelPosX + ($\RCEFMenu\AnchorSizeX / 2)

x99 = $OffsetX
y99 = $\RCEFMenu\OffsetY
z99 = 0
w99 = 1.6
Resource\RCEFText\Text = ref ResourceSectionHeader
run = CommandList\RCEFMenu\DrawNormalText

$\RCEFMenu\OffsetY = $\RCEFMenu\OffsetY + ($\RCEFText\TexelSize * w99) + ($\RCEFMenu\PaddingY * $\RCEFMenu\AspectRatio)

$MinY = $\RCEFMenu\OffsetY
$MaxY = $MinY + $\RCEFText\TexelSize * w99
$OffsetX = $\RCEFMenu\PanelPosX + $\RCEFMenu\AnchorSizeX

x99 = $OffsetX
y99 = $\RCEFMenu\OffsetY
w99 = 1.5
Resource\RCEFText\Text = ref ResourceOptionUnlit
if $\RCEFCore\UnlitView == 0
	run = CommandList\RCEFMenu\DrawNormalText
else
	run = CommandList\RCEFMenu\DrawSelectedText
endif

$OffsetX = $OffsetX + (5 * $\RCEFText\TexelSize * $\RCEFText\WidthMulti * w99 / $\RCEFMenu\AspectRatio)

$MinX_Unlit = x99
$MaxX_Unlit = $OffsetX

$OffsetX = $OffsetX + ($\RCEFMenu\PaddingX * 1.5)

x99 = $OffsetX
Resource\RCEFText\Text = ref ResourceOptionHideUI
if $\RCEFCore\HideGameUI == 0
	run = CommandList\RCEFMenu\DrawNormalText
else
	run = CommandList\RCEFMenu\DrawSelectedText
endif

$OffsetX = $OffsetX + (6 * $\RCEFText\TexelSize * $\RCEFText\WidthMulti * w99 / $\RCEFMenu\AspectRatio)

$MinX_HideUI = x99
$MaxX_HideUI = $OffsetX

$OffsetX = $OffsetX + ($\RCEFMenu\PaddingX * 1.5)

x99 = $OffsetX
Resource\RCEFText\Text = ref ResourceOptionCamCoords
if $\RCEFCore\CamCoords == 0
	run = CommandList\RCEFMenu\DrawNormalText
else
	run = CommandList\RCEFMenu\DrawSelectedText
endif

$OffsetX = $OffsetX + (8 * $\RCEFText\TexelSize * $\RCEFText\WidthMulti * w99 / $\RCEFMenu\AspectRatio)

$MinX_CamCoords = x99
$MaxX_CamCoords = $OffsetX

$\RCEFMenu\OffsetY = $\RCEFMenu\OffsetY + ($\RCEFText\TexelSize * w99) + ($\RCEFMenu\PaddingY * $\RCEFMenu\AspectRatio)