; Show Zones Menu Section of RCEFShaders

namespace = RCEFMenu\ShowZones

[Constants]
global $MinY = 0
global $MaxY = 0

global $MinX_Death = 0
global $MaxX_Death = 0

global $MinX_Teleport = 0
global $MaxX_Teleport = 0

[KeySelectMode]
key = VK_LBUTTON
run = CommandListMakeSelection

[CommandListMakeSelection]
if cursor_y >= $MinY && cursor_y <= $MaxY
	if cursor_x >= $MinX_Death && cursor_x <= $MaxX_Death
		$\RCEFCore\DeathZones = !$\RCEFCore\DeathZones
	elif cursor_x >= $MinX_Teleport && cursor_x <= $MaxX_Teleport
		$\RCEFCore\TeleportZones = !$\RCEFCore\TeleportZones
	endif
endif

[ResourceSectionHeader]
type = Buffer
format = R8_UINT
data = "Show Zones"

[ResourceOptionDeath]
type = Buffer
format = R8_UINT
data = "Death"

[ResourceOptionTeleport]
type = Buffer
format = R8_UINT
data = "Teleport"

[CommandListDrawSection]
local $OffsetX = $\RCEFMenu\PanelPosX + ($\RCEFMenu\AnchorSizeX / 2)

x99 = $OffsetX
y99 = $\RCEFMenu\OffsetY
z99 = 0
w99 = 1.6
Resource\RCEFText\Text = ref ResourceSectionHeader
run = CommandList\RCEFMenu\DrawNormalText

$\RCEFMenu\OffsetY = $\RCEFMenu\OffsetY + ($\RCEFText\TexelSize * w99) + ($\RCEFMenu\PaddingY * $\RCEFMenu\AspectRatio)

$MinY = $\RCEFMenu\OffsetY
$MaxY = $MinY + $\RCEFText\TexelSize * w99
$OffsetX = $\RCEFMenu\PanelPosX + $\RCEFMenu\AnchorSizeX

x99 = $OffsetX
y99 = $\RCEFMenu\OffsetY
w99 = 1.5
Resource\RCEFText\Text = ref ResourceOptionDeath
if $\RCEFCore\DeathZones == 0
	run = CommandList\RCEFMenu\DrawNormalText
else
	run = CommandList\RCEFMenu\DrawSelectedText
endif

$OffsetX = $OffsetX + (5 * $\RCEFText\TexelSize * $\RCEFText\WidthMulti * w99 / $\RCEFMenu\AspectRatio)

$MinX_Death = x99
$MaxX_Death = $OffsetX

$OffsetX = $OffsetX + ($\RCEFMenu\PaddingX * 1.5)

x99 = $OffsetX
Resource\RCEFText\Text = ref ResourceOptionTeleport
if $\RCEFCore\TeleportZones == 0
	run = CommandList\RCEFMenu\DrawNormalText
else
	run = CommandList\RCEFMenu\DrawSelectedText
endif

$OffsetX = $OffsetX + (8 * $\RCEFText\TexelSize * $\RCEFText\WidthMulti * w99 / $\RCEFMenu\AspectRatio)

$MinX_Teleport = x99
$MaxX_Teleport = $OffsetX

$\RCEFMenu\OffsetY = $\RCEFMenu\OffsetY + ($\RCEFText\TexelSize * w99) + ($\RCEFMenu\PaddingY * $\RCEFMenu\AspectRatio)