; Solid AIC Menu Section of RCEFShaders

namespace = RCEFMenu\SolidAIC

[Constants]
global $MinY = 0
global $MaxY = 0

global $MinX_Region = 0
global $MaxX_Region = 0

global $MinX_Tiles = 0
global $MaxX_Tiles = 0

[KeySelectMode]
key = VK_LBUTTON
run = CommandListMakeSelection

[CommandListMakeSelection]
if cursor_y >= $MinY && cursor_y <= $MaxY
	if cursor_x >= $MinX_Region && cursor_x <= $MaxX_Region
		$\RCEFCore\SolidAICRegion = !$\RCEFCore\SolidAICRegion
	elif cursor_x >= $MinX_Tiles && cursor_x <= $MaxX_Tiles
		$\RCEFCore\SolidAICTiles = !$\RCEFCore\SolidAICTiles
	endif
endif

[ResourceSectionHeader]
type = Buffer
format = R8_UINT
data = "Solid AIC"

[ResourceOptionRegion]
type = Buffer
format = R8_UINT
data = "Regions"

[ResourceOptionTiles]
type = Buffer
format = R8_UINT
data = "Tiles"

[CommandListDrawSection]
local $OffsetX = $\RCEFMenu\PanelPosX + ($\RCEFMenu\AnchorSizeX / 2)

x99 = $OffsetX
y99 = $\RCEFMenu\OffsetY
z99 = 0
w99 = 1.6
Resource\RCEFText\Text = ref ResourceSectionHeader
run = CommandList\RCEFMenu\DrawNormalText

$\RCEFMenu\OffsetY = $\RCEFMenu\OffsetY + ($\RCEFText\TexelSize * w99) + ($\RCEFMenu\PaddingY * $\RCEFMenu\AspectRatio)

$MinY = $\RCEFMenu\OffsetY
$MaxY = $MinY + $\RCEFText\TexelSize * w99
$OffsetX = $\RCEFMenu\PanelPosX + $\RCEFMenu\AnchorSizeX

x99 = $OffsetX
y99 = $\RCEFMenu\OffsetY
w99 = 1.5
Resource\RCEFText\Text = ref ResourceOptionRegion
if $\RCEFCore\SolidAICRegion == 0
	run = CommandList\RCEFMenu\DrawNormalText
else
	run = CommandList\RCEFMenu\DrawSelectedText
endif

$OffsetX = $OffsetX + (7 * $\RCEFText\TexelSize * $\RCEFText\WidthMulti * w99 / $\RCEFMenu\AspectRatio)

$MinX_Region = x99
$MaxX_Region = $OffsetX

$OffsetX = $OffsetX + ($\RCEFMenu\PaddingX * 1.5)

x99 = $OffsetX
Resource\RCEFText\Text = ref ResourceOptionTiles
if $\RCEFCore\SolidAICTiles == 0
	run = CommandList\RCEFMenu\DrawNormalText
else
	run = CommandList\RCEFMenu\DrawSelectedText
endif

$OffsetX = $OffsetX + (5 * $\RCEFText\TexelSize * $\RCEFText\WidthMulti * w99 / $\RCEFMenu\AspectRatio)

$MinX_Tiles = x99
$MaxX_Tiles = $OffsetX

$\RCEFMenu\OffsetY = $\RCEFMenu\OffsetY + ($\RCEFText\TexelSize * w99) + ($\RCEFMenu\PaddingY * $\RCEFMenu\AspectRatio)