; Solid AIC Menu Section of RCEFShaders

namespace = RCEFMenu\SolidAIC

; Hitbox state -----------------------------

[Constants]
global $MinY = 0
global $MaxY = 0

global $MinX_Region = 0
global $MaxX_Region = 0

global $MinX_Tiles = 0
global $MaxX_Tiles = 0

; Click handling ---------------------------

[KeySelectMode]
condition = $\RCEFMenu\IsOpen
key = VK_LBUTTON
run = CommandListMakeSelection

[CommandListMakeSelection]
if cursor_y >= $MinY && cursor_y <= $MaxY
	if cursor_x >= $MinX_Region && cursor_x <= $MaxX_Region
		$\RCEFCore\SolidAICRegion = !$\RCEFCore\SolidAICRegion
	elif cursor_x >= $MinX_Tiles && cursor_x <= $MaxX_Tiles
		$\RCEFCore\SolidAICTiles = !$\RCEFCore\SolidAICTiles
	endif
endif

; Text resources ---------------------------

[ResourceSectionHeader]
type = Buffer
format = R8_UINT
data = "Solid AIC"

[ResourceOptionRegion]
type = Buffer
format = R8_UINT
data = "Regions"

[ResourceOptionTiles]
type = Buffer
format = R8_UINT
data = "Tiles"

; Section rendering ------------------------

[CommandListDrawSection]
; Section header
local $OffsetX = $\RCEFMenu\PanelPosX + ($\RCEFMenu\AnchorSizeX / 2)

z99 = 0
w99 = 1.6
x99 = $OffsetX
y99 = $\RCEFMenu\OffsetY
Resource\RCEFText\Text = ref ResourceSectionHeader
run = CommandList\RCEFMenu\DrawNormalText

$\RCEFMenu\OffsetY = $\RCEFMenu\OffsetY + ($\RCEFText\TexelSize * w99) + ($\RCEFMenu\PaddingY * $\RCEFLibrary\AspectRatio)

; Option row bounds and starting position
$MinY = $\RCEFMenu\OffsetY
$MaxY = $MinY + $\RCEFText\TexelSize * w99
$OffsetX = $\RCEFMenu\PanelPosX + $\RCEFMenu\AnchorSizeX

; Option: Regions
w99 = 1.5
x99 = $OffsetX
y99 = $\RCEFMenu\OffsetY
Resource\RCEFText\Text = ref ResourceOptionRegion
if $\RCEFCore\SolidAICRegion == 0
	run = CommandList\RCEFMenu\DrawNormalText
else
	run = CommandList\RCEFMenu\DrawSelectedText
endif

$OffsetX = $OffsetX + (7 * $\RCEFText\TexelSize * $\RCEFText\WidthMulti * w99 / $\RCEFLibrary\AspectRatio)

$MinX_Region = x99
$MaxX_Region = $OffsetX

$OffsetX = $OffsetX + ($\RCEFMenu\PaddingX * 1.5)

; Option: Tiles
x99 = $OffsetX
Resource\RCEFText\Text = ref ResourceOptionTiles
if $\RCEFCore\SolidAICTiles == 0
	run = CommandList\RCEFMenu\DrawNormalText
else
	run = CommandList\RCEFMenu\DrawSelectedText
endif

$OffsetX = $OffsetX + (5 * $\RCEFText\TexelSize * $\RCEFText\WidthMulti * w99 / $\RCEFLibrary\AspectRatio)

$MinX_Tiles = x99
$MaxX_Tiles = $OffsetX

; Leave spacing for the next menu section
$\RCEFMenu\OffsetY = $\RCEFMenu\OffsetY + ($\RCEFText\TexelSize * w99) + ($\RCEFMenu\PaddingY * $\RCEFLibrary\AspectRatio)