; Show Zones Menu Section of RCEFShaders

namespace = RCEFMenu\Volumes

[Constants]
global $MinY_L1 = 0
global $MaxY_L1 = 0

global $MinY_L2 = 0
global $MaxY_L2 = 0

global $MinX_InvisWalls = 0
global $MaxX_InvisWalls = 0

global $MinX_KillZones = 0
global $MaxX_KillZones = 0

global $MinX_TPZones = 0
global $MaxX_TPZones = 0

[KeySelectMode]
condition = $\RCEFMenu\IsOpen
key = VK_LBUTTON
run = CommandListMakeSelection

[CommandListMakeSelection]
if cursor_y >= $MinY_L1 && cursor_y <= $MaxY_L1
	if cursor_x >= $MinX_InvisWalls && cursor_x <= $MaxX_InvisWalls
		$\RCEFCore\InvisWalls = !$\RCEFCore\InvisWalls
	endif
elif cursor_y >= $MinY_L2 && cursor_y <= $MaxY_L2
	if cursor_x >= $MinX_KillZones && cursor_x <= $MaxX_KillZones
		$\RCEFCore\KillZones = !$\RCEFCore\KillZones
    elif cursor_x >= $MinX_TPZones && cursor_x <= $MaxX_TPZones
		$\RCEFCore\TPZones = !$\RCEFCore\TPZones
    endif
endif

[ResourceSectionHeader]
type = Buffer
format = R8_UINT
data = "Hidden Volumes"

[ResourceOptionInvisWalls]
type = Buffer
format = R8_UINT
data = "Invisible-Walls"

[ResourceOptionKillZone]
type = Buffer
format = R8_UINT
data = "Kill-Zone"

[ResourceOptionTPZone]
type = Buffer
format = R8_UINT
data = "TP-Zone"

[CommandListDrawSection]
local $OffsetX = $\RCEFMenu\PanelPosX + ($\RCEFMenu\AnchorSizeX / 2)

x99 = $OffsetX
y99 = $\RCEFMenu\OffsetY
z99 = 0
w99 = 1.6
Resource\RCEFText\Text = ref ResourceSectionHeader
run = CommandList\RCEFMenu\DrawNormalText

$\RCEFMenu\OffsetY = $\RCEFMenu\OffsetY + ($\RCEFText\TexelSize * w99) + ($\RCEFMenu\PaddingY * $\RCEFLibrary\AspectRatio)

$MinY_L1 = $\RCEFMenu\OffsetY
$MaxY_L1 = $MinY_L1 + $\RCEFText\TexelSize * w99
$OffsetX = $\RCEFMenu\PanelPosX + $\RCEFMenu\AnchorSizeX

w99 = 1.5
x99 = $OffsetX
y99 = $\RCEFMenu\OffsetY
Resource\RCEFText\Text = ref ResourceOptionInvisWalls
if $\RCEFCore\InvisWalls == 0
	run = CommandList\RCEFMenu\DrawNormalText
else
	run = CommandList\RCEFMenu\DrawSelectedText
endif

$OffsetX = $OffsetX + (15 * $\RCEFText\TexelSize * $\RCEFText\WidthMulti * w99 / $\RCEFLibrary\AspectRatio)

$MinX_InvisWalls = x99
$MaxX_InvisWalls = $OffsetX

$OffsetX = $\RCEFMenu\PanelPosX + $\RCEFMenu\AnchorSizeX
$\RCEFMenu\OffsetY = $\RCEFMenu\OffsetY + ($\RCEFText\TexelSize * w99) + ($\RCEFMenu\PaddingY * $\RCEFLibrary\AspectRatio)

$MinY_L2 = $\RCEFMenu\OffsetY
$MaxY_L2 = $MinY_L2 + $\RCEFText\TexelSize * w99

x99 = $OffsetX
y99 = $\RCEFMenu\OffsetY
Resource\RCEFText\Text = ref ResourceOptionKillZone
if $\RCEFCore\KillZones == 0
	run = CommandList\RCEFMenu\DrawNormalText
else
	run = CommandList\RCEFMenu\DrawSelectedText
endif

$OffsetX = $OffsetX + (9 * $\RCEFText\TexelSize * $\RCEFText\WidthMulti * w99 / $\RCEFLibrary\AspectRatio)

$MinX_KillZones = x99
$MaxX_KillZones = $OffsetX

$OffsetX = $OffsetX + ($\RCEFMenu\PaddingX * 1.5)

x99 = $OffsetX
Resource\RCEFText\Text = ref ResourceOptionTPZone
if $\RCEFCore\TPZones == 0
	run = CommandList\RCEFMenu\DrawNormalText
else
	run = CommandList\RCEFMenu\DrawSelectedText
endif

$OffsetX = $OffsetX + (7 * $\RCEFText\TexelSize * $\RCEFText\WidthMulti * w99 / $\RCEFLibrary\AspectRatio)

$MinX_TPZones = x99
$MaxX_TPZones = $OffsetX

$\RCEFMenu\OffsetY = $\RCEFMenu\OffsetY + ($\RCEFText\TexelSize * w99) + ($\RCEFMenu\PaddingY * $\RCEFLibrary\AspectRatio)