; Menu module of RCEFShaders

namespace = RCEFMenu

[Constants]
; Configurable
global persist $PanelPosX = 0.2
global persist $PanelPosY = 0.2
global $PanelSizeX = 0.3
global $PanelSizeY = 0.35
global $AnchorSizeX = 0.02
global $AnchorSizeY = 0.02
global $DividerSize = 0.002
global $PaddingX = 0.01
global $PaddingY = 0.01

; DO NOT configure these
global $IsOpen = 0
global $IsDragging = 0
global $CanDrag = 0
global $OffsetY = 0
global $AspectRatio = 1

[KeyOpenMenu]
key = VK_ALT VK_END
type = toggle
$IsOpen = 1

[KeyDragMenu]
condition = $IsOpen && $CanDrag
key = VK_LBUTTON
type = hold
$IsDragging = 1

[Present]
if $IsOpen && window_width > 0 && window_height > 0
	$AspectRatio = window_width / window_height

    local $DragMaxX = $PanelPosX + $AnchorSizeX
    local $DragMaxY = $PanelPosY + ($AnchorSizeY * $AspectRatio)
    $CanDrag = cursor_x >= $PanelPosX && cursor_x <= $DragMaxX && cursor_y >= $PanelPosY && cursor_y <= $DragMaxY
	if $IsDragging
		$PanelPosX = cursor_x - ($AnchorSizeX / 2)
		$PanelPosY = cursor_y - ($AnchorSizeY / 2) * $AspectRatio

		if $PanelPosX > 1 - $AnchorSizeX
			$PanelPosX = 1 - $AnchorSizeX
		endif
		if $PanelPosX < 0
			$PanelPosX = 0
		endif

		if $PanelPosY > 1 - ($AnchorSizeY * $AspectRatio)
			$PanelPosY = 1 - ($AnchorSizeY * $AspectRatio)
		endif
		if $PanelPosY < 0
			$PanelPosY = 0
		endif
	endif

	$OffsetY = $PanelPosY

	local $savedX99 = x99
	local $savedY99 = y99
	local $savedZ99 = z99
	local $savedW99 = w99

	run = CustomShaderDrawBase
	run = CustomShaderDrawDivider
	run = CommandList\RCEFMenu\Foliage\DrawSection
	run = CustomShaderDrawDivider
	run = CommandList\RCEFMenu\InvisWalls\DrawSection
	run = CustomShaderDrawDivider
	run = CommandList\RCEFMenu\ShowZones\DrawSection
	run = CustomShaderDrawDivider
	run = CommandList\RCEFMenu\SolidAIC\DrawSection
	run = CustomShaderDrawDivider
	run = CommandList\RCEFMenu\Misc\DrawSection

	x99 = $savedX99
	y99 = $savedY99
	z99 = $savedZ99
	w99 = $savedW99
else
	$CanDrag = 0
endif

[ResourceColorWhite]
type = Buffer
data = R32_FLOAT 1 1 1 1

[ResourceColorBlack]
type = Buffer
data = R32_FLOAT 0 0 0 1

[ResourceColorYellow]
type = Buffer
data = R32_FLOAT 1 1 0 1

[ResourceColorBase]
type = Buffer
data = R32_FLOAT 0.08 0.08 0.08 0.75

[ResourceColorDivider]
type = Buffer
data = R32_FLOAT 0.5 0.5 0.5 1

[ResourceBufferThing]
type = Buffer
data = R32_FLOAT 0.2 0.2 0.2 0.4

[CustomShaderDrawDivider]
vs = Shaders/Draw2D.hlsl
ps = Shaders/Draw2D.hlsl
cs = null
ds = null
gs = null
hs = null
cull = none
topology = triangle_strip
blend = ADD SRC_ALPHA INV_SRC_ALPHA
o0 = set_viewport no_view_cache bb
x99 = $PanelPosX
y99 = $OffsetY
z99 = $PanelSizeX
w99 = $DividerSize * $AspectRatio
ps-cb0 = ref ResourceColorDivider
ps-t1 = null
draw = 4, 0
$OffsetY = $OffsetY + w99 + ($PaddingY * $AspectRatio)

[CommandListDrawNormalText]
Resource\RCEFText\TextData = null
Resource\RCEFText\BackColor = null
Resource\RCEFText\TextColor = ref ResourceColorWhite
run = CommandList\RCEFText\PrintText

[CommandListDrawSelectedText]
Resource\RCEFText\TextData = null
Resource\RCEFText\BackColor = ref ResourceColorYellow
Resource\RCEFText\TextColor = ref ResourceColorBlack
run = CommandList\RCEFText\PrintText

[ResourceMenuTitle]
type = Buffer
format = R8_UINT
data = "RCEFShaders (ALT + END)"

[CustomShaderDrawBase]
vs = Shaders/Draw2D.hlsl
ps = Shaders/Draw2D.hlsl
cs = null
ds = null
gs = null
hs = null
cull = none
topology = triangle_strip
blend = ADD SRC_ALPHA INV_SRC_ALPHA
o0 = set_viewport no_view_cache bb

x99 = $PanelPosX
y99 = $PanelPosY
z99 = $PanelSizeX
w99 = $PanelSizeY * $AspectRatio
ps-cb0 = ref ResourceColorBase
ps-t1 = null
draw = 4, 0

z99 = $AnchorSizeX
w99 = $AnchorSizeY * $AspectRatio
ps-cb0 = ref ResourceColorWhite
ps-t1 = null
draw = 4, 0

x99 = $PanelPosX + ($PanelSizeX / 2)
y99 = $PanelPosY + ($AnchorSizeY / 4) * $AspectRatio
z99 = 1
w99 = 2
Resource\RCEFText\Text = ref ResourceMenuTitle
Resource\RCEFText\TextColor = ref ResourceColorYellow
run = CommandList\RCEFText\PrintText

$OffsetY = $OffsetY + ($\RCEFText\TexelSize * w99) + ($PaddingY * $AspectRatio)