; Text module of RCEFShaders

namespace = RCEFText

; API --------------------------------------
; Usage Instructions:
;
;	[ResourceDataExample]
;	type = Buffer
;	data = R32_FLOAT 0.5  0.5    1     1
;	                  X    Y   Align  Size
;
;	[ResourceColorExample]
;	type = Buffer
;	data = R32_FLOAT 1 1 0 1
;	                (R G B A) [0..1]
;
;	[ResourceTextExample]
;	type = Buffer
;	format = R8_UINT
;	data = "Hello World"
;
; Data can be provided with IniParams like this:
;	x99 = X Position (left...right) [0..1]
;	y99 = Y Position (top...bottom) [0..1]
;	z99 = Horizontal Alignment: 0 - Left, 1 - Center, 2 - Right
;	w99 = Scale Multiplier: 1 gives a line height of 16/1080 of the viewport
; Or with a buffer:
;	Resource\RCEFText\TextData = Data data in place of IniParams
;
;	Resource\RCEFText\BackColor = (Optional) Color of the text background
;	Resource\RCEFText\TextColor = Color of the text itself
;	Resource\RCEFText\Text = Text to display
;	run = CommandList\RCEFText\PrintText (Display the text)

[ResourceBackColor]

[ResourceTextColor]

[ResourceTextData]

[ResourceText]

[CommandListPrintText]
if ResourceText !== null && $\RCEFLibrary\HasValidViewport && (w99 > 0 || ResourceTextData !== null)
	run = CustomShaderLayout
	run = CustomShaderDraw
endif
ResourceText = null
ResourceTextData = null
ResourceTextColor = null
ResourceBackColor = null

; Implementation ---------------------------

[ResourceFont]
filename = Font/LiberationMono-Bold.dds

[ResourceLayout]
type = StructuredBuffer
stride = 16
array = 4096

[CustomShaderLayout]
cs = Shaders/DrawText.hlsl
cs-t1 = ref ResourceFont
cs-t2 = ref ResourceText
if ResourceTextData !== null
	cs-cb0 = ref ResourceTextData
else
	cs-cb0 = null
endif
cs-u0 = ResourceLayout
dispatch = 1, 1, 1
cs-t1 = null
cs-t2 = null
cs-cb0 = null
cs-u0 = null

[CustomShaderDraw]
vs = Shaders/DrawText.hlsl
ps = Shaders/DrawText.hlsl
cs = null
ds = null
gs = null
hs = null

cull = none
depth_enable = false
stencil_enable = false
scissor_enable = false
depth_clip_enable = false
topology = triangle_list
blend = ADD SRC_ALPHA INV_SRC_ALPHA

run = BuiltInCommandListUnbindAllRenderTargets
o0 = set_viewport no_view_cache bb

vs-t1 = ref ResourceFont
vs-t2 = ref ResourceText
vs-t3 = ResourceLayout
vs-t4 = Resource\RCEFLibrary\ViewportSize
ps-t1 = ref ResourceFont
if ResourceTextData !== null
	vs-cb0 = ref ResourceTextData
else
	vs-cb0 = null
endif
ps-cb0 = null
ps-cb1 = ref ResourceBackColor
ps-cb2 = ref ResourceTextColor

; 4096 slots * 6 vertices = 24576 vertices
; But the final layout stores block bounds leaving 4095 character slots
; Thus, 4095 slots * 6 vertices = 24570
draw = 24570, 0

vs-t1 = null
vs-t2 = null
vs-t3 = null
vs-t4 = null
ps-t1 = null
vs-cb0 = null
ps-cb0 = null
ps-cb1 = null
ps-cb2 = null