; Core module of RCEFShaders

namespace = RCEFCore

; Feature Toggles --------------------------

[Constants]
; Multi-Mode Features
global persist $FoliageMode = 0
global persist $InvisWallMode = 0

; Gameplay Volumes
global persist $DeathZones = 0
global persist $TeleportZones = 0

; Solid AIC System
global persist $SolidAICRegion = 0
global persist $SolidAICTiles = 0

; Misc Features
global persist $UnlitView = 0
global persist $CamCoords = 0
global persist $HideGameUI = 0

; Global status flags
global $InGameWorld = 1

; Startup Info -----------------------------

[ResourceInitText]
type = Buffer
format = R8_UINT
data = "RCEFShaders Initialized! Press ALT + END for toggle menu."

[ResourceInitTextData]
type = Buffer
data = R32_FLOAT 0.5 0.8 1 1.8

[Present]
$InGameWorld = $\RCEFLibrary\HasSceneDepth && $\RCEFLibrary\HasViewConstants
if $InGameWorld
	local $InitMsgCountdown
	if $\RCEFMenu\IsOpen
		$InitMsgCountdown = 0
	else
		local $InitMsgLastFrame
		local $InitMsgInitialized

		if !$InitMsgInitialized
			$InitMsgCountdown = 5
			$InitMsgLastFrame = -1
			$InitMsgInitialized = 1
		endif

		if $InitMsgCountdown > 0
			if $InitMsgLastFrame < 0
				$InitMsgLastFrame = time
			endif

			if time > $InitMsgLastFrame
				$InitMsgCountdown = $InitMsgCountdown - (time - $InitMsgLastFrame)
			endif

			Resource\RCEFText\Text = ref ResourceInitText
			Resource\RCEFText\TextData = ref ResourceInitTextData
			Resource\RCEFText\BackColor = ref Resource\RCEFMenu\ColorYellow
			Resource\RCEFText\TextColor = ref Resource\RCEFMenu\ColorBlack
			run = CommandList\RCEFText\PrintText

			$InitMsgLastFrame = time
		endif
	endif
endif
