; Library for RCEFShaders

namespace = RCEFLibrary

[Constants]
global $HasSceneDepth = 0

[ResourceSceneDepth]

; Implementation ---------------------------

[Present]
post $HasSceneDepth = 0

[CommandListCaptureSceneDepth]
if !$HasSceneDepth
	ResourceSceneDepth = ref ps-t1
	$HasSceneDepth = 1
endif

; Source shaders ---------------------------

[ShaderOverride_SceneDepth_17b280fb09bf16fd]
hash = 17b280fb09bf16fd
allow_duplicate_hash = true
run = CommandListCaptureSceneDepth

[ShaderOverride_SceneDepth_e5c79df0d5b00481]
hash = e5c79df0d5b00481
allow_duplicate_hash = true
run = CommandListCaptureSceneDepth

[ShaderOverride_SceneDepth_37eacbc3c84bb392]
hash = 37eacbc3c84bb392
allow_duplicate_hash = true
run = CommandListCaptureSceneDepth

[ShaderOverride_SceneDepth_bb9293bfbf23a3c5]
hash = bb9293bfbf23a3c5
allow_duplicate_hash = true
run = CommandListCaptureSceneDepth

[ShaderOverride_SceneDepth_d6cd817025f6567c]
hash = d6cd817025f6567c
allow_duplicate_hash = true
run = CommandListCaptureSceneDepth

[ShaderOverride_SceneDepth_6f33660185243d05]
hash = 6f33660185243d05
allow_duplicate_hash = true
run = CommandListCaptureSceneDepth

[ShaderOverride_SceneDepth_5e5271b322c7bd5c]
hash = 5e5271b322c7bd5c
allow_duplicate_hash = true
run = CommandListCaptureSceneDepth

[ShaderOverride_SceneDepth_530cf926c33e99ee]
hash = 530cf926c33e99ee
allow_duplicate_hash = true
run = CommandListCaptureSceneDepth

[ShaderOverride_SceneDepth_743f991c236b6dde]
hash = 743f991c236b6dde
allow_duplicate_hash = true
run = CommandListCaptureSceneDepth

[ShaderOverride_SceneDepth_b8360398f113f945]
hash = b8360398f113f945
allow_duplicate_hash = true
run = CommandListCaptureSceneDepth

[ShaderOverride_SceneDepth_30462d509b56535f]
hash = 30462d509b56535f
allow_duplicate_hash = true
run = CommandListCaptureSceneDepth

[ShaderOverride_SceneDepth_addb4925f6e279b8]
hash = addb4925f6e279b8
allow_duplicate_hash = true
run = CommandListCaptureSceneDepth

[ShaderOverride_SceneDepth_955aa6eb61756d0c]
hash = 955aa6eb61756d0c
allow_duplicate_hash = true
run = CommandListCaptureSceneDepth

[ShaderOverride_SceneDepth_44719138df0a512b]
hash = 44719138df0a512b
allow_duplicate_hash = true
run = CommandListCaptureSceneDepth

[ShaderOverride_SceneDepth_2fd35c280da6db61]
hash = 2fd35c280da6db61
allow_duplicate_hash = true
run = CommandListCaptureSceneDepth

[ShaderOverride_SceneDepth_512cc3b9be7a6ae0]
hash = 512cc3b9be7a6ae0
allow_duplicate_hash = true
run = CommandListCaptureSceneDepth