; Library for RCEFShaders

namespace = RCEFLibrary

[Constants]
global $HasValidViewport = 0
global $AspectRatio = 1

[ResourceViewportSize]
type = Texture2D
format = R8_UNORM
array = 1
mips = 1
msaa = 1

; Implementation ---------------------------

[Present]
if bb !== null
	$HasValidViewport = window_width > 0 && window_height > 0
	if $HasValidViewport
		$AspectRatio = window_width / window_height
	endif

	ResourceViewportSize = copy_description bb
else
	$HasValidViewport = 0
endif