; Feature Module of RCEFShaders

namespace = RCEFShaders\InvisWalls

; Feature Impl -----------------------------

[Constants]
; Optional depth test that culls invisibe walls that are occluded by other invisible walls.
; When disabled, the walls will stack. Only really necessary in places with high wall density.
; Not the best but works well enough.
global $selfDepthTest = 0

[CommandListRender]
if $\RCEFCore\InvisWalls && $\RCEFCore\InGameWorld && $\RCEFLibrary\HasValidViewport
	run = CommandListPrepSelfDepth
	run = CustomShaderInvisWalls
endif

; Depth mask for self depth test -----------

[ResourceSelfDepth]
format = DXGI_FORMAT_D32_FLOAT
bind_flags = depth_stencil
array = 1
mips = 1
msaa = 1

[CommandListPrepSelfDepth]
if $selfDepthTest && bb !== null
	; Copy the info from the backbody so we match the resolution
	ResourceSelfDepth = copy_description bb
endif

; Render invisible walls -------------------

[ResourceWallData]
type = Buffer
data = R32_FLOAT 0.0 1.0 1.0  500.0
;                 ^   ^   ^   ^- Max Distance (0 for no limit)
;                 R   G   B  Color

[ResourceWallIB_Valley4]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = Meshes\InvisWall_Valley4_IB.buf

[ResourceWallVB_Valley4]
type = Buffer
stride = 20
filename = Meshes\InvisWall_Valley4_VB.buf

[ResourceWallIB_Wuling]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = Meshes\InvisWall_Wuling_IB.buf

[ResourceWallVB_Wuling]
type = Buffer
stride = 20
filename = Meshes\InvisWall_Wuling_VB.buf

[CustomShaderInvisWalls]
vs = ..\..\Core\Shaders\DrawVolume.hlsl
ps = ..\..\Core\Shaders\DrawVolume.hlsl
cs = null
ds = null
gs = null
hs = null
cull = front
topology = triangle_list
blend = ADD SRC_ALPHA INV_SRC_ALPHA
run = BuiltInCommandListUnbindAllRenderTargets
o0 = set_viewport no_view_cache bb

depth_enable = true
depth_write_mask = all
depth_func = greater_equal
if $selfDepthTest && ResourceSelfDepth !== null
    oD = ResourceSelfDepth
    clear = ResourceSelfDepth
endif

vs-cb0 = ref Resource\RCEFLibrary\CameraCB
ps-t1 = ref Resource\RCEFLibrary\ViewportSize
ps-t2 = ref Resource\RCEFLibrary\SceneDepth
ps-cb0 = ref ResourceWallData

if $\RCEFCore\ActiveScene == 0
	vb0 = ref ResourceWallVB_Valley4
	ib = ref ResourceWallIB_Valley4
	drawindexed = 36036, 0, 0
else if $\RCEFCore\ActiveScene == 1
	vb0 = ref ResourceWallVB_Wuling
	ib = ref ResourceWallIB_Wuling
	drawindexed = 72144, 0, 0
endif