; Feature Module of RCEFShaders

namespace = RCEFShaders\KillZones

; Feature Impl -----------------------------

[CommandListRender]
if $\RCEFCore\KillZones && $\RCEFCore\InGameWorld && $\RCEFLibrary\HasValidViewport
	run = CustomShaderKillZones
endif

; Render kill zones ------------------------

[ResourceZoneData]
type = Buffer
data = R32_FLOAT 1.0 0.0 0.0  500.0
;                 ^   ^   ^   ^- Max Distance (0 for no limit)
;                 R   G   B  Color

[ResourceZoneIB_Valley4]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = Meshes\KillZone_Valley4_IB.buf

[ResourceZoneVB_Valley4]
type = Buffer
stride = 20
filename = Meshes\KillZone_Valley4_VB.buf

[ResourceZoneIB_Wuling]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = Meshes\KillZone_Wuling_IB.buf

[ResourceZoneVB_Wuling]
type = Buffer
stride = 20
filename = Meshes\KillZone_Wuling_VB.buf

[CustomShaderKillZones]
