; Feature Module of RCEFShaders

namespace = RCEFShaders\TPZones

; Feature Impl -----------------------------

[CommandListRender]
if $\RCEFCore\TPZones && $\RCEFCore\InGameWorld && $\RCEFLibrary\HasValidViewport
	run = CustomShaderTPZones
endif

; Render teleport zones --------------------

[ResourceZoneData]
type = Buffer
data = R32_FLOAT 0.5 0.0 1.0  500.0
;                 ^   ^   ^   ^- Max Distance (0 for no limit)
;                 R   G   B  Color

; Seems there aren't any in Valley 4
; [ResourceZoneIB_Valley4]
; type = Buffer
; format = DXGI_FORMAT_R32_UINT
; filename = Meshes\TPZone_Valley4_IB.buf
; 
; [ResourceZoneVB_Valley4]
; type = Buffer
; stride = 20
; filename = Meshes\TPZone_Valley4_VB.buf

[ResourceZoneIB_Wuling]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = Meshes\TPZone_Wuling_IB.buf

[ResourceZoneVB_Wuling]
type = Buffer
stride = 20
filename = Meshes\TPZone_Wuling_VB.buf

[CustomShaderTPZones]
vs = ..\..\Core\Shaders\DrawVolume.hlsl
ps = ..\..\Core\Shaders\DrawVolume.hlsl
cs = null
ds = null
gs = null
hs = null
cull = front
topology = triangle_list
blend = ADD SRC_ALPHA INV_SRC_ALPHA
run = BuiltInCommandListUnbindAllRenderTargets
o0 = set_viewport no_view_cache bb

vs-cb0 = ref Resource\RCEFLibrary\CameraCB
ps-t1 = ref Resource\RCEFLibrary\ViewportSize
ps-t2 = ref Resource\RCEFLibrary\SceneDepth
ps-cb0 = ref ResourceZoneData

if $\RCEFCore\ActiveScene == 0
	; There's none in Valley 4
else if $\RCEFCore\ActiveScene == 1
	vb0 = ref ResourceZoneVB_Wuling
	ib = ref ResourceZoneIB_Wuling
	drawindexed = 2040, 0, 0
endif