; Feature Module of RCEFShaders

namespace = RCEFShaders\TPZones

; Feature Impl -----------------------------

[CommandListRender]
if $\RCEFCore\TPZones && $\RCEFCore\InGameWorld && $\RCEFLibrary\HasValidViewport
	run = CustomShaderTPZones
endif

; Render teleport zones --------------------

[ResourceZoneData]
type = Buffer
data = R32_FLOAT 0.5 0.0 1.0  500.0
;                 ^   ^   ^   ^- Max Distance (0 for no limit)
;                 R   G   B  Color

[ResourceZoneIB_Valley4]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = Meshes\KillZone_Valley4_IB.buf

[ResourceZoneVB_Valley4]
type = Buffer
stride = 20
filename = Meshes\KillZone_Valley4_VB.buf

[ResourceZoneIB_Wuling]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = Meshes\KillZone_Wuling_IB.buf

[ResourceZoneVB_Wuling]
type = Buffer
stride = 20
filename = Meshes\KillZone_Wuling_VB.buf

[CustomShaderTPZones]